// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _hw5_ex1_HH_
#define _hw5_ex1_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "hw5_ex1_temp1.h"
#include "hw5_ex1_temp2.h"

namespace ap_rtl {

struct hw5_ex1 : public sc_module {
    // Port declarations 10
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<960> > A;
    sc_in< sc_lv<960> > B_i;
    sc_out< sc_lv<960> > B_o;
    sc_out< sc_logic > B_o_ap_vld;


    // Module declarations
    hw5_ex1(sc_module_name name);
    SC_HAS_PROCESS(hw5_ex1);

    ~hw5_ex1();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    hw5_ex1_temp1* temp1_U;
    hw5_ex1_temp2* temp2_U;
    sc_signal< sc_lv<8> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<5> > i_2_fu_235_p2;
    sc_signal< sc_lv<5> > i_2_reg_642;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > icmp_ln55_fu_229_p2;
    sc_signal< sc_lv<5> > i_fu_247_p2;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<1> > icmp_ln11_fu_365_p2;
    sc_signal< sc_lv<32> > temp1_q0;
    sc_signal< sc_lv<32> > temp1_load_reg_674;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<64> > zext_ln12_1_fu_382_p1;
    sc_signal< sc_lv<64> > zext_ln12_1_reg_679;
    sc_signal< sc_lv<5> > i_1_fu_387_p2;
    sc_signal< sc_lv<5> > i_1_reg_689;
    sc_signal< sc_lv<5> > i_3_fu_490_p2;
    sc_signal< sc_lv<5> > i_3_reg_702;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<1> > icmp_ln17_fu_484_p2;
    sc_signal< sc_lv<960> > or_ln18_fu_633_p2;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<5> > temp1_address0;
    sc_signal< sc_logic > temp1_ce0;
    sc_signal< sc_logic > temp1_we0;
    sc_signal< sc_lv<32> > temp1_d0;
    sc_signal< sc_lv<5> > temp1_address1;
    sc_signal< sc_logic > temp1_ce1;
    sc_signal< sc_lv<32> > temp1_q1;
    sc_signal< sc_lv<5> > temp2_address0;
    sc_signal< sc_logic > temp2_ce0;
    sc_signal< sc_logic > temp2_we0;
    sc_signal< sc_lv<32> > temp2_d0;
    sc_signal< sc_lv<32> > temp2_q0;
    sc_signal< sc_lv<5> > i_0_reg_167;
    sc_signal< sc_lv<5> > i_0_i_reg_178;
    sc_signal< sc_lv<1> > icmp_ln5_fu_241_p2;
    sc_signal< sc_lv<5> > i_0_i3_reg_189;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<960> > out_w_0_i_reg_201;
    sc_signal< sc_lv<5> > i_0_i5_reg_212;
    sc_signal< sc_lv<64> > zext_ln55_fu_224_p1;
    sc_signal< sc_lv<64> > zext_ln6_fu_253_p1;
    sc_signal< sc_lv<64> > zext_ln12_fu_377_p1;
    sc_signal< sc_lv<64> > zext_ln12_2_fu_393_p1;
    sc_signal< sc_lv<64> > zext_ln18_fu_496_p1;
    sc_signal< sc_lv<32> > select_ln12_1_fu_475_p3;
    sc_signal< sc_lv<10> > tmp_1_fu_258_p3;
    sc_signal< sc_lv<10> > empty_8_fu_266_p2;
    sc_signal< sc_lv<1> > icmp_ln6_fu_272_p2;
    sc_signal< sc_lv<10> > sub_ln6_fu_287_p2;
    sc_signal< sc_lv<10> > sub_ln6_2_fu_299_p2;
    sc_signal< sc_lv<960> > tmp_4_fu_278_p4;
    sc_signal< sc_lv<10> > sub_ln6_1_fu_293_p2;
    sc_signal< sc_lv<10> > select_ln6_fu_305_p3;
    sc_signal< sc_lv<10> > select_ln6_2_fu_320_p3;
    sc_signal< sc_lv<10> > sub_ln6_3_fu_328_p2;
    sc_signal< sc_lv<960> > select_ln6_1_fu_313_p3;
    sc_signal< sc_lv<960> > zext_ln6_1_fu_334_p1;
    sc_signal< sc_lv<960> > zext_ln6_2_fu_338_p1;
    sc_signal< sc_lv<960> > lshr_ln6_fu_342_p2;
    sc_signal< sc_lv<960> > lshr_ln6_1_fu_348_p2;
    sc_signal< sc_lv<960> > and_ln6_fu_354_p2;
    sc_signal< sc_lv<5> > add_ln12_fu_371_p2;
    sc_signal< sc_lv<32> > add_ln12_2_fu_398_p2;
    sc_signal< sc_lv<32> > add_ln12_3_fu_404_p2;
    sc_signal< sc_lv<32> > mul_ln12_fu_413_p0;
    sc_signal< sc_lv<65> > mul_ln12_fu_413_p2;
    sc_signal< sc_lv<65> > sub_ln12_fu_419_p2;
    sc_signal< sc_lv<31> > tmp_6_fu_433_p4;
    sc_signal< sc_lv<31> > tmp_7_fu_447_p4;
    sc_signal< sc_lv<1> > tmp_5_fu_425_p3;
    sc_signal< sc_lv<32> > sext_ln12_1_fu_443_p1;
    sc_signal< sc_lv<32> > sext_ln12_2_fu_457_p1;
    sc_signal< sc_lv<32> > select_ln12_fu_461_p3;
    sc_signal< sc_lv<32> > sub_ln12_1_fu_469_p2;
    sc_signal< sc_lv<10> > shl_ln_fu_501_p3;
    sc_signal< sc_lv<10> > empty_11_fu_509_p2;
    sc_signal< sc_lv<1> > icmp_ln18_fu_515_p2;
    sc_signal< sc_lv<10> > sub_ln18_fu_525_p2;
    sc_signal< sc_lv<10> > select_ln18_fu_531_p3;
    sc_signal< sc_lv<10> > select_ln18_2_fu_547_p3;
    sc_signal< sc_lv<10> > select_ln18_1_fu_539_p3;
    sc_signal< sc_lv<10> > sub_ln18_1_fu_555_p2;
    sc_signal< sc_lv<960> > zext_ln18_1_fu_521_p1;
    sc_signal< sc_lv<960> > zext_ln18_2_fu_561_p1;
    sc_signal< sc_lv<960> > shl_ln18_fu_573_p2;
    sc_signal< sc_lv<960> > tmp_8_fu_579_p4;
    sc_signal< sc_lv<960> > zext_ln18_3_fu_565_p1;
    sc_signal< sc_lv<960> > zext_ln18_4_fu_569_p1;
    sc_signal< sc_lv<960> > shl_ln18_1_fu_597_p2;
    sc_signal< sc_lv<960> > lshr_ln18_fu_603_p2;
    sc_signal< sc_lv<960> > and_ln18_fu_609_p2;
    sc_signal< sc_lv<960> > xor_ln18_fu_615_p2;
    sc_signal< sc_lv<960> > select_ln18_3_fu_589_p3;
    sc_signal< sc_lv<960> > and_ln18_1_fu_621_p2;
    sc_signal< sc_lv<960> > and_ln18_2_fu_627_p2;
    sc_signal< sc_lv<8> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<8> ap_ST_fsm_state1;
    static const sc_lv<8> ap_ST_fsm_state2;
    static const sc_lv<8> ap_ST_fsm_state3;
    static const sc_lv<8> ap_ST_fsm_state4;
    static const sc_lv<8> ap_ST_fsm_state5;
    static const sc_lv<8> ap_ST_fsm_state6;
    static const sc_lv<8> ap_ST_fsm_state7;
    static const sc_lv<8> ap_ST_fsm_state8;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<5> ap_const_lv5_1;
    static const sc_lv<5> ap_const_lv5_1E;
    static const sc_lv<10> ap_const_lv10_1F;
    static const sc_lv<32> ap_const_lv32_3BF;
    static const sc_lv<10> ap_const_lv10_3BF;
    static const sc_lv<960> ap_const_lv960_lc_1;
    static const sc_lv<5> ap_const_lv5_1D;
    static const sc_lv<5> ap_const_lv5_1F;
    static const sc_lv<65> ap_const_lv65_155555556;
    static const sc_lv<65> ap_const_lv65_0;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<32> ap_const_lv32_22;
    static const sc_lv<32> ap_const_lv32_40;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_B_o();
    void thread_B_o_ap_vld();
    void thread_add_ln12_2_fu_398_p2();
    void thread_add_ln12_3_fu_404_p2();
    void thread_add_ln12_fu_371_p2();
    void thread_and_ln18_1_fu_621_p2();
    void thread_and_ln18_2_fu_627_p2();
    void thread_and_ln18_fu_609_p2();
    void thread_and_ln6_fu_354_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_empty_11_fu_509_p2();
    void thread_empty_8_fu_266_p2();
    void thread_i_1_fu_387_p2();
    void thread_i_2_fu_235_p2();
    void thread_i_3_fu_490_p2();
    void thread_i_fu_247_p2();
    void thread_icmp_ln11_fu_365_p2();
    void thread_icmp_ln17_fu_484_p2();
    void thread_icmp_ln18_fu_515_p2();
    void thread_icmp_ln55_fu_229_p2();
    void thread_icmp_ln5_fu_241_p2();
    void thread_icmp_ln6_fu_272_p2();
    void thread_lshr_ln18_fu_603_p2();
    void thread_lshr_ln6_1_fu_348_p2();
    void thread_lshr_ln6_fu_342_p2();
    void thread_mul_ln12_fu_413_p0();
    void thread_mul_ln12_fu_413_p2();
    void thread_or_ln18_fu_633_p2();
    void thread_select_ln12_1_fu_475_p3();
    void thread_select_ln12_fu_461_p3();
    void thread_select_ln18_1_fu_539_p3();
    void thread_select_ln18_2_fu_547_p3();
    void thread_select_ln18_3_fu_589_p3();
    void thread_select_ln18_fu_531_p3();
    void thread_select_ln6_1_fu_313_p3();
    void thread_select_ln6_2_fu_320_p3();
    void thread_select_ln6_fu_305_p3();
    void thread_sext_ln12_1_fu_443_p1();
    void thread_sext_ln12_2_fu_457_p1();
    void thread_shl_ln18_1_fu_597_p2();
    void thread_shl_ln18_fu_573_p2();
    void thread_shl_ln_fu_501_p3();
    void thread_sub_ln12_1_fu_469_p2();
    void thread_sub_ln12_fu_419_p2();
    void thread_sub_ln18_1_fu_555_p2();
    void thread_sub_ln18_fu_525_p2();
    void thread_sub_ln6_1_fu_293_p2();
    void thread_sub_ln6_2_fu_299_p2();
    void thread_sub_ln6_3_fu_328_p2();
    void thread_sub_ln6_fu_287_p2();
    void thread_temp1_address0();
    void thread_temp1_address1();
    void thread_temp1_ce0();
    void thread_temp1_ce1();
    void thread_temp1_d0();
    void thread_temp1_we0();
    void thread_temp2_address0();
    void thread_temp2_ce0();
    void thread_temp2_d0();
    void thread_temp2_we0();
    void thread_tmp_1_fu_258_p3();
    void thread_tmp_4_fu_278_p4();
    void thread_tmp_5_fu_425_p3();
    void thread_tmp_6_fu_433_p4();
    void thread_tmp_7_fu_447_p4();
    void thread_tmp_8_fu_579_p4();
    void thread_xor_ln18_fu_615_p2();
    void thread_zext_ln12_1_fu_382_p1();
    void thread_zext_ln12_2_fu_393_p1();
    void thread_zext_ln12_fu_377_p1();
    void thread_zext_ln18_1_fu_521_p1();
    void thread_zext_ln18_2_fu_561_p1();
    void thread_zext_ln18_3_fu_565_p1();
    void thread_zext_ln18_4_fu_569_p1();
    void thread_zext_ln18_fu_496_p1();
    void thread_zext_ln55_fu_224_p1();
    void thread_zext_ln6_1_fu_334_p1();
    void thread_zext_ln6_2_fu_338_p1();
    void thread_zext_ln6_fu_253_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
