// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "hw5_ex1.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic hw5_ex1::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic hw5_ex1::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<8> hw5_ex1::ap_ST_fsm_state1 = "1";
const sc_lv<8> hw5_ex1::ap_ST_fsm_state2 = "10";
const sc_lv<8> hw5_ex1::ap_ST_fsm_state3 = "100";
const sc_lv<8> hw5_ex1::ap_ST_fsm_state4 = "1000";
const sc_lv<8> hw5_ex1::ap_ST_fsm_state5 = "10000";
const sc_lv<8> hw5_ex1::ap_ST_fsm_state6 = "100000";
const sc_lv<8> hw5_ex1::ap_ST_fsm_state7 = "1000000";
const sc_lv<8> hw5_ex1::ap_ST_fsm_state8 = "10000000";
const sc_lv<32> hw5_ex1::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> hw5_ex1::ap_const_lv32_1 = "1";
const sc_lv<1> hw5_ex1::ap_const_lv1_0 = "0";
const sc_lv<32> hw5_ex1::ap_const_lv32_2 = "10";
const sc_lv<32> hw5_ex1::ap_const_lv32_3 = "11";
const sc_lv<1> hw5_ex1::ap_const_lv1_1 = "1";
const sc_lv<32> hw5_ex1::ap_const_lv32_4 = "100";
const sc_lv<32> hw5_ex1::ap_const_lv32_6 = "110";
const sc_lv<32> hw5_ex1::ap_const_lv32_7 = "111";
const sc_lv<5> hw5_ex1::ap_const_lv5_0 = "00000";
const sc_lv<32> hw5_ex1::ap_const_lv32_5 = "101";
const sc_lv<5> hw5_ex1::ap_const_lv5_1 = "1";
const sc_lv<5> hw5_ex1::ap_const_lv5_1E = "11110";
const sc_lv<10> hw5_ex1::ap_const_lv10_1F = "11111";
const sc_lv<32> hw5_ex1::ap_const_lv32_3BF = "1110111111";
const sc_lv<10> hw5_ex1::ap_const_lv10_3BF = "1110111111";
const sc_lv<960> hw5_ex1::ap_const_lv960_lc_1 = "111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111";
const sc_lv<5> hw5_ex1::ap_const_lv5_1D = "11101";
const sc_lv<5> hw5_ex1::ap_const_lv5_1F = "11111";
const sc_lv<65> hw5_ex1::ap_const_lv65_155555556 = "101010101010101010101010101010110";
const sc_lv<65> hw5_ex1::ap_const_lv65_0 = "00000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> hw5_ex1::ap_const_lv32_1F = "11111";
const sc_lv<32> hw5_ex1::ap_const_lv32_22 = "100010";
const sc_lv<32> hw5_ex1::ap_const_lv32_40 = "1000000";
const bool hw5_ex1::ap_const_boolean_1 = true;

hw5_ex1::hw5_ex1(sc_module_name name) : sc_module(name), mVcdFile(0) {
    temp1_U = new hw5_ex1_temp1("temp1_U");
    temp1_U->clk(ap_clk);
    temp1_U->reset(ap_rst);
    temp1_U->address0(temp1_address0);
    temp1_U->ce0(temp1_ce0);
    temp1_U->we0(temp1_we0);
    temp1_U->d0(temp1_d0);
    temp1_U->q0(temp1_q0);
    temp1_U->address1(temp1_address1);
    temp1_U->ce1(temp1_ce1);
    temp1_U->q1(temp1_q1);
    temp2_U = new hw5_ex1_temp2("temp2_U");
    temp2_U->clk(ap_clk);
    temp2_U->reset(ap_rst);
    temp2_U->address0(temp2_address0);
    temp2_U->ce0(temp2_ce0);
    temp2_U->we0(temp2_we0);
    temp2_U->d0(temp2_d0);
    temp2_U->q0(temp2_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_B_o);
    sensitive << ( B_i );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln17_fu_484_p2 );
    sensitive << ( out_w_0_i_reg_201 );

    SC_METHOD(thread_B_o_ap_vld);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln17_fu_484_p2 );

    SC_METHOD(thread_add_ln12_2_fu_398_p2);
    sensitive << ( temp1_q0 );
    sensitive << ( temp1_q1 );

    SC_METHOD(thread_add_ln12_3_fu_404_p2);
    sensitive << ( temp1_load_reg_674 );
    sensitive << ( add_ln12_2_fu_398_p2 );

    SC_METHOD(thread_add_ln12_fu_371_p2);
    sensitive << ( i_0_i3_reg_189 );

    SC_METHOD(thread_and_ln18_1_fu_621_p2);
    sensitive << ( out_w_0_i_reg_201 );
    sensitive << ( xor_ln18_fu_615_p2 );

    SC_METHOD(thread_and_ln18_2_fu_627_p2);
    sensitive << ( and_ln18_fu_609_p2 );
    sensitive << ( select_ln18_3_fu_589_p3 );

    SC_METHOD(thread_and_ln18_fu_609_p2);
    sensitive << ( shl_ln18_1_fu_597_p2 );
    sensitive << ( lshr_ln18_fu_603_p2 );

    SC_METHOD(thread_and_ln6_fu_354_p2);
    sensitive << ( lshr_ln6_fu_342_p2 );
    sensitive << ( lshr_ln6_1_fu_348_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln55_fu_229_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln55_fu_229_p2 );

    SC_METHOD(thread_empty_11_fu_509_p2);
    sensitive << ( shl_ln_fu_501_p3 );

    SC_METHOD(thread_empty_8_fu_266_p2);
    sensitive << ( tmp_1_fu_258_p3 );

    SC_METHOD(thread_i_1_fu_387_p2);
    sensitive << ( i_0_i3_reg_189 );

    SC_METHOD(thread_i_2_fu_235_p2);
    sensitive << ( i_0_reg_167 );

    SC_METHOD(thread_i_3_fu_490_p2);
    sensitive << ( i_0_i5_reg_212 );

    SC_METHOD(thread_i_fu_247_p2);
    sensitive << ( i_0_i_reg_178 );

    SC_METHOD(thread_icmp_ln11_fu_365_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( i_0_i3_reg_189 );

    SC_METHOD(thread_icmp_ln17_fu_484_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( i_0_i5_reg_212 );

    SC_METHOD(thread_icmp_ln18_fu_515_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( shl_ln_fu_501_p3 );
    sensitive << ( empty_11_fu_509_p2 );

    SC_METHOD(thread_icmp_ln55_fu_229_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_167 );

    SC_METHOD(thread_icmp_ln5_fu_241_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( i_0_i_reg_178 );

    SC_METHOD(thread_icmp_ln6_fu_272_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln5_fu_241_p2 );
    sensitive << ( tmp_1_fu_258_p3 );
    sensitive << ( empty_8_fu_266_p2 );

    SC_METHOD(thread_lshr_ln18_fu_603_p2);
    sensitive << ( zext_ln18_4_fu_569_p1 );

    SC_METHOD(thread_lshr_ln6_1_fu_348_p2);
    sensitive << ( zext_ln6_2_fu_338_p1 );

    SC_METHOD(thread_lshr_ln6_fu_342_p2);
    sensitive << ( select_ln6_1_fu_313_p3 );
    sensitive << ( zext_ln6_1_fu_334_p1 );

    SC_METHOD(thread_mul_ln12_fu_413_p0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( add_ln12_3_fu_404_p2 );

    SC_METHOD(thread_mul_ln12_fu_413_p2);
    sensitive << ( mul_ln12_fu_413_p0 );

    SC_METHOD(thread_or_ln18_fu_633_p2);
    sensitive << ( and_ln18_1_fu_621_p2 );
    sensitive << ( and_ln18_2_fu_627_p2 );

    SC_METHOD(thread_select_ln12_1_fu_475_p3);
    sensitive << ( tmp_5_fu_425_p3 );
    sensitive << ( sext_ln12_2_fu_457_p1 );
    sensitive << ( sub_ln12_1_fu_469_p2 );

    SC_METHOD(thread_select_ln12_fu_461_p3);
    sensitive << ( tmp_5_fu_425_p3 );
    sensitive << ( sext_ln12_1_fu_443_p1 );
    sensitive << ( sext_ln12_2_fu_457_p1 );

    SC_METHOD(thread_select_ln18_1_fu_539_p3);
    sensitive << ( shl_ln_fu_501_p3 );
    sensitive << ( empty_11_fu_509_p2 );
    sensitive << ( icmp_ln18_fu_515_p2 );

    SC_METHOD(thread_select_ln18_2_fu_547_p3);
    sensitive << ( shl_ln_fu_501_p3 );
    sensitive << ( icmp_ln18_fu_515_p2 );
    sensitive << ( sub_ln18_fu_525_p2 );

    SC_METHOD(thread_select_ln18_3_fu_589_p3);
    sensitive << ( icmp_ln18_fu_515_p2 );
    sensitive << ( shl_ln18_fu_573_p2 );
    sensitive << ( tmp_8_fu_579_p4 );

    SC_METHOD(thread_select_ln18_fu_531_p3);
    sensitive << ( shl_ln_fu_501_p3 );
    sensitive << ( empty_11_fu_509_p2 );
    sensitive << ( icmp_ln18_fu_515_p2 );

    SC_METHOD(thread_select_ln6_1_fu_313_p3);
    sensitive << ( A );
    sensitive << ( icmp_ln6_fu_272_p2 );
    sensitive << ( tmp_4_fu_278_p4 );

    SC_METHOD(thread_select_ln6_2_fu_320_p3);
    sensitive << ( tmp_1_fu_258_p3 );
    sensitive << ( icmp_ln6_fu_272_p2 );
    sensitive << ( sub_ln6_1_fu_293_p2 );

    SC_METHOD(thread_select_ln6_fu_305_p3);
    sensitive << ( icmp_ln6_fu_272_p2 );
    sensitive << ( sub_ln6_fu_287_p2 );
    sensitive << ( sub_ln6_2_fu_299_p2 );

    SC_METHOD(thread_sext_ln12_1_fu_443_p1);
    sensitive << ( tmp_6_fu_433_p4 );

    SC_METHOD(thread_sext_ln12_2_fu_457_p1);
    sensitive << ( tmp_7_fu_447_p4 );

    SC_METHOD(thread_shl_ln18_1_fu_597_p2);
    sensitive << ( zext_ln18_3_fu_565_p1 );

    SC_METHOD(thread_shl_ln18_fu_573_p2);
    sensitive << ( zext_ln18_1_fu_521_p1 );
    sensitive << ( zext_ln18_2_fu_561_p1 );

    SC_METHOD(thread_shl_ln_fu_501_p3);
    sensitive << ( i_0_i5_reg_212 );

    SC_METHOD(thread_sub_ln12_1_fu_469_p2);
    sensitive << ( select_ln12_fu_461_p3 );

    SC_METHOD(thread_sub_ln12_fu_419_p2);
    sensitive << ( mul_ln12_fu_413_p2 );

    SC_METHOD(thread_sub_ln18_1_fu_555_p2);
    sensitive << ( select_ln18_fu_531_p3 );

    SC_METHOD(thread_sub_ln18_fu_525_p2);
    sensitive << ( shl_ln_fu_501_p3 );

    SC_METHOD(thread_sub_ln6_1_fu_293_p2);
    sensitive << ( tmp_1_fu_258_p3 );

    SC_METHOD(thread_sub_ln6_2_fu_299_p2);
    sensitive << ( tmp_1_fu_258_p3 );
    sensitive << ( empty_8_fu_266_p2 );

    SC_METHOD(thread_sub_ln6_3_fu_328_p2);
    sensitive << ( select_ln6_fu_305_p3 );

    SC_METHOD(thread_sub_ln6_fu_287_p2);
    sensitive << ( tmp_1_fu_258_p3 );
    sensitive << ( empty_8_fu_266_p2 );

    SC_METHOD(thread_temp1_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( zext_ln12_1_fu_382_p1 );
    sensitive << ( zext_ln6_fu_253_p1 );
    sensitive << ( zext_ln12_fu_377_p1 );

    SC_METHOD(thread_temp1_address1);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( zext_ln12_2_fu_393_p1 );

    SC_METHOD(thread_temp1_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_temp1_ce1);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_temp1_d0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( and_ln6_fu_354_p2 );

    SC_METHOD(thread_temp1_we0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln5_fu_241_p2 );

    SC_METHOD(thread_temp2_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln12_1_reg_679 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln55_fu_224_p1 );
    sensitive << ( zext_ln18_fu_496_p1 );

    SC_METHOD(thread_temp2_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_temp2_d0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( select_ln12_1_fu_475_p3 );

    SC_METHOD(thread_temp2_we0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln55_fu_229_p2 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_tmp_1_fu_258_p3);
    sensitive << ( i_0_i_reg_178 );

    SC_METHOD(thread_tmp_4_fu_278_p4);
    sensitive << ( A );

    SC_METHOD(thread_tmp_5_fu_425_p3);
    sensitive << ( add_ln12_3_fu_404_p2 );

    SC_METHOD(thread_tmp_6_fu_433_p4);
    sensitive << ( sub_ln12_fu_419_p2 );

    SC_METHOD(thread_tmp_7_fu_447_p4);
    sensitive << ( mul_ln12_fu_413_p2 );

    SC_METHOD(thread_tmp_8_fu_579_p4);
    sensitive << ( shl_ln18_fu_573_p2 );

    SC_METHOD(thread_xor_ln18_fu_615_p2);
    sensitive << ( and_ln18_fu_609_p2 );

    SC_METHOD(thread_zext_ln12_1_fu_382_p1);
    sensitive << ( i_0_i3_reg_189 );

    SC_METHOD(thread_zext_ln12_2_fu_393_p1);
    sensitive << ( i_1_fu_387_p2 );

    SC_METHOD(thread_zext_ln12_fu_377_p1);
    sensitive << ( add_ln12_fu_371_p2 );

    SC_METHOD(thread_zext_ln18_1_fu_521_p1);
    sensitive << ( temp2_q0 );

    SC_METHOD(thread_zext_ln18_2_fu_561_p1);
    sensitive << ( select_ln18_2_fu_547_p3 );

    SC_METHOD(thread_zext_ln18_3_fu_565_p1);
    sensitive << ( select_ln18_1_fu_539_p3 );

    SC_METHOD(thread_zext_ln18_4_fu_569_p1);
    sensitive << ( sub_ln18_1_fu_555_p2 );

    SC_METHOD(thread_zext_ln18_fu_496_p1);
    sensitive << ( i_0_i5_reg_212 );

    SC_METHOD(thread_zext_ln55_fu_224_p1);
    sensitive << ( i_0_reg_167 );

    SC_METHOD(thread_zext_ln6_1_fu_334_p1);
    sensitive << ( select_ln6_2_fu_320_p3 );

    SC_METHOD(thread_zext_ln6_2_fu_338_p1);
    sensitive << ( sub_ln6_3_fu_328_p2 );

    SC_METHOD(thread_zext_ln6_fu_253_p1);
    sensitive << ( i_0_i_reg_178 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln55_fu_229_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln11_fu_365_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln17_fu_484_p2 );
    sensitive << ( icmp_ln5_fu_241_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "00000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "hw5_ex1_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, A, "(port)A");
    sc_trace(mVcdFile, B_i, "(port)B_i");
    sc_trace(mVcdFile, B_o, "(port)B_o");
    sc_trace(mVcdFile, B_o_ap_vld, "(port)B_o_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, i_2_fu_235_p2, "i_2_fu_235_p2");
    sc_trace(mVcdFile, i_2_reg_642, "i_2_reg_642");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, icmp_ln55_fu_229_p2, "icmp_ln55_fu_229_p2");
    sc_trace(mVcdFile, i_fu_247_p2, "i_fu_247_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, icmp_ln11_fu_365_p2, "icmp_ln11_fu_365_p2");
    sc_trace(mVcdFile, temp1_q0, "temp1_q0");
    sc_trace(mVcdFile, temp1_load_reg_674, "temp1_load_reg_674");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, zext_ln12_1_fu_382_p1, "zext_ln12_1_fu_382_p1");
    sc_trace(mVcdFile, zext_ln12_1_reg_679, "zext_ln12_1_reg_679");
    sc_trace(mVcdFile, i_1_fu_387_p2, "i_1_fu_387_p2");
    sc_trace(mVcdFile, i_1_reg_689, "i_1_reg_689");
    sc_trace(mVcdFile, i_3_fu_490_p2, "i_3_fu_490_p2");
    sc_trace(mVcdFile, i_3_reg_702, "i_3_reg_702");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, icmp_ln17_fu_484_p2, "icmp_ln17_fu_484_p2");
    sc_trace(mVcdFile, or_ln18_fu_633_p2, "or_ln18_fu_633_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, temp1_address0, "temp1_address0");
    sc_trace(mVcdFile, temp1_ce0, "temp1_ce0");
    sc_trace(mVcdFile, temp1_we0, "temp1_we0");
    sc_trace(mVcdFile, temp1_d0, "temp1_d0");
    sc_trace(mVcdFile, temp1_address1, "temp1_address1");
    sc_trace(mVcdFile, temp1_ce1, "temp1_ce1");
    sc_trace(mVcdFile, temp1_q1, "temp1_q1");
    sc_trace(mVcdFile, temp2_address0, "temp2_address0");
    sc_trace(mVcdFile, temp2_ce0, "temp2_ce0");
    sc_trace(mVcdFile, temp2_we0, "temp2_we0");
    sc_trace(mVcdFile, temp2_d0, "temp2_d0");
    sc_trace(mVcdFile, temp2_q0, "temp2_q0");
    sc_trace(mVcdFile, i_0_reg_167, "i_0_reg_167");
    sc_trace(mVcdFile, i_0_i_reg_178, "i_0_i_reg_178");
    sc_trace(mVcdFile, icmp_ln5_fu_241_p2, "icmp_ln5_fu_241_p2");
    sc_trace(mVcdFile, i_0_i3_reg_189, "i_0_i3_reg_189");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, out_w_0_i_reg_201, "out_w_0_i_reg_201");
    sc_trace(mVcdFile, i_0_i5_reg_212, "i_0_i5_reg_212");
    sc_trace(mVcdFile, zext_ln55_fu_224_p1, "zext_ln55_fu_224_p1");
    sc_trace(mVcdFile, zext_ln6_fu_253_p1, "zext_ln6_fu_253_p1");
    sc_trace(mVcdFile, zext_ln12_fu_377_p1, "zext_ln12_fu_377_p1");
    sc_trace(mVcdFile, zext_ln12_2_fu_393_p1, "zext_ln12_2_fu_393_p1");
    sc_trace(mVcdFile, zext_ln18_fu_496_p1, "zext_ln18_fu_496_p1");
    sc_trace(mVcdFile, select_ln12_1_fu_475_p3, "select_ln12_1_fu_475_p3");
    sc_trace(mVcdFile, tmp_1_fu_258_p3, "tmp_1_fu_258_p3");
    sc_trace(mVcdFile, empty_8_fu_266_p2, "empty_8_fu_266_p2");
    sc_trace(mVcdFile, icmp_ln6_fu_272_p2, "icmp_ln6_fu_272_p2");
    sc_trace(mVcdFile, sub_ln6_fu_287_p2, "sub_ln6_fu_287_p2");
    sc_trace(mVcdFile, sub_ln6_2_fu_299_p2, "sub_ln6_2_fu_299_p2");
    sc_trace(mVcdFile, tmp_4_fu_278_p4, "tmp_4_fu_278_p4");
    sc_trace(mVcdFile, sub_ln6_1_fu_293_p2, "sub_ln6_1_fu_293_p2");
    sc_trace(mVcdFile, select_ln6_fu_305_p3, "select_ln6_fu_305_p3");
    sc_trace(mVcdFile, select_ln6_2_fu_320_p3, "select_ln6_2_fu_320_p3");
    sc_trace(mVcdFile, sub_ln6_3_fu_328_p2, "sub_ln6_3_fu_328_p2");
    sc_trace(mVcdFile, select_ln6_1_fu_313_p3, "select_ln6_1_fu_313_p3");
    sc_trace(mVcdFile, zext_ln6_1_fu_334_p1, "zext_ln6_1_fu_334_p1");
    sc_trace(mVcdFile, zext_ln6_2_fu_338_p1, "zext_ln6_2_fu_338_p1");
    sc_trace(mVcdFile, lshr_ln6_fu_342_p2, "lshr_ln6_fu_342_p2");
    sc_trace(mVcdFile, lshr_ln6_1_fu_348_p2, "lshr_ln6_1_fu_348_p2");
    sc_trace(mVcdFile, and_ln6_fu_354_p2, "and_ln6_fu_354_p2");
    sc_trace(mVcdFile, add_ln12_fu_371_p2, "add_ln12_fu_371_p2");
    sc_trace(mVcdFile, add_ln12_2_fu_398_p2, "add_ln12_2_fu_398_p2");
    sc_trace(mVcdFile, add_ln12_3_fu_404_p2, "add_ln12_3_fu_404_p2");
    sc_trace(mVcdFile, mul_ln12_fu_413_p0, "mul_ln12_fu_413_p0");
    sc_trace(mVcdFile, mul_ln12_fu_413_p2, "mul_ln12_fu_413_p2");
    sc_trace(mVcdFile, sub_ln12_fu_419_p2, "sub_ln12_fu_419_p2");
    sc_trace(mVcdFile, tmp_6_fu_433_p4, "tmp_6_fu_433_p4");
    sc_trace(mVcdFile, tmp_7_fu_447_p4, "tmp_7_fu_447_p4");
    sc_trace(mVcdFile, tmp_5_fu_425_p3, "tmp_5_fu_425_p3");
    sc_trace(mVcdFile, sext_ln12_1_fu_443_p1, "sext_ln12_1_fu_443_p1");
    sc_trace(mVcdFile, sext_ln12_2_fu_457_p1, "sext_ln12_2_fu_457_p1");
    sc_trace(mVcdFile, select_ln12_fu_461_p3, "select_ln12_fu_461_p3");
    sc_trace(mVcdFile, sub_ln12_1_fu_469_p2, "sub_ln12_1_fu_469_p2");
    sc_trace(mVcdFile, shl_ln_fu_501_p3, "shl_ln_fu_501_p3");
    sc_trace(mVcdFile, empty_11_fu_509_p2, "empty_11_fu_509_p2");
    sc_trace(mVcdFile, icmp_ln18_fu_515_p2, "icmp_ln18_fu_515_p2");
    sc_trace(mVcdFile, sub_ln18_fu_525_p2, "sub_ln18_fu_525_p2");
    sc_trace(mVcdFile, select_ln18_fu_531_p3, "select_ln18_fu_531_p3");
    sc_trace(mVcdFile, select_ln18_2_fu_547_p3, "select_ln18_2_fu_547_p3");
    sc_trace(mVcdFile, select_ln18_1_fu_539_p3, "select_ln18_1_fu_539_p3");
    sc_trace(mVcdFile, sub_ln18_1_fu_555_p2, "sub_ln18_1_fu_555_p2");
    sc_trace(mVcdFile, zext_ln18_1_fu_521_p1, "zext_ln18_1_fu_521_p1");
    sc_trace(mVcdFile, zext_ln18_2_fu_561_p1, "zext_ln18_2_fu_561_p1");
    sc_trace(mVcdFile, shl_ln18_fu_573_p2, "shl_ln18_fu_573_p2");
    sc_trace(mVcdFile, tmp_8_fu_579_p4, "tmp_8_fu_579_p4");
    sc_trace(mVcdFile, zext_ln18_3_fu_565_p1, "zext_ln18_3_fu_565_p1");
    sc_trace(mVcdFile, zext_ln18_4_fu_569_p1, "zext_ln18_4_fu_569_p1");
    sc_trace(mVcdFile, shl_ln18_1_fu_597_p2, "shl_ln18_1_fu_597_p2");
    sc_trace(mVcdFile, lshr_ln18_fu_603_p2, "lshr_ln18_fu_603_p2");
    sc_trace(mVcdFile, and_ln18_fu_609_p2, "and_ln18_fu_609_p2");
    sc_trace(mVcdFile, xor_ln18_fu_615_p2, "xor_ln18_fu_615_p2");
    sc_trace(mVcdFile, select_ln18_3_fu_589_p3, "select_ln18_3_fu_589_p3");
    sc_trace(mVcdFile, and_ln18_1_fu_621_p2, "and_ln18_1_fu_621_p2");
    sc_trace(mVcdFile, and_ln18_2_fu_627_p2, "and_ln18_2_fu_627_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("hw5_ex1.hdltvin.dat");
    mHdltvoutHandle.open("hw5_ex1.hdltvout.dat");
}

hw5_ex1::~hw5_ex1() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete temp1_U;
    delete temp2_U;
}

void hw5_ex1::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln5_fu_241_p2.read()))) {
        i_0_i3_reg_189 = ap_const_lv5_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        i_0_i3_reg_189 = i_1_reg_689.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        i_0_i5_reg_212 = i_3_reg_702.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(icmp_ln11_fu_365_p2.read(), ap_const_lv1_1))) {
        i_0_i5_reg_212 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln5_fu_241_p2.read()))) {
        i_0_i_reg_178 = i_fu_247_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln55_fu_229_p2.read(), ap_const_lv1_0))) {
        i_0_i_reg_178 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln17_fu_484_p2.read()))) {
        i_0_reg_167 = i_2_reg_642.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_167 = ap_const_lv5_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        out_w_0_i_reg_201 = or_ln18_fu_633_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(icmp_ln11_fu_365_p2.read(), ap_const_lv1_1))) {
        out_w_0_i_reg_201 = B_i.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        i_1_reg_689 = i_1_fu_387_p2.read();
        temp1_load_reg_674 = temp1_q0.read();
        zext_ln12_1_reg_679 = zext_ln12_1_fu_382_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_2_reg_642 = i_2_fu_235_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        i_3_reg_702 = i_3_fu_490_p2.read();
    }
}

void hw5_ex1::thread_B_o() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln17_fu_484_p2.read()))) {
        B_o = out_w_0_i_reg_201.read();
    } else {
        B_o = B_i.read();
    }
}

void hw5_ex1::thread_B_o_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln17_fu_484_p2.read()))) {
        B_o_ap_vld = ap_const_logic_1;
    } else {
        B_o_ap_vld = ap_const_logic_0;
    }
}

void hw5_ex1::thread_add_ln12_2_fu_398_p2() {
    add_ln12_2_fu_398_p2 = (!temp1_q0.read().is_01() || !temp1_q1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(temp1_q0.read()) + sc_biguint<32>(temp1_q1.read()));
}

void hw5_ex1::thread_add_ln12_3_fu_404_p2() {
    add_ln12_3_fu_404_p2 = (!add_ln12_2_fu_398_p2.read().is_01() || !temp1_load_reg_674.read().is_01())? sc_lv<32>(): (sc_biguint<32>(add_ln12_2_fu_398_p2.read()) + sc_biguint<32>(temp1_load_reg_674.read()));
}

void hw5_ex1::thread_add_ln12_fu_371_p2() {
    add_ln12_fu_371_p2 = (!i_0_i3_reg_189.read().is_01() || !ap_const_lv5_1F.is_01())? sc_lv<5>(): (sc_biguint<5>(i_0_i3_reg_189.read()) + sc_bigint<5>(ap_const_lv5_1F));
}

void hw5_ex1::thread_and_ln18_1_fu_621_p2() {
    and_ln18_1_fu_621_p2 = (out_w_0_i_reg_201.read() & xor_ln18_fu_615_p2.read());
}

void hw5_ex1::thread_and_ln18_2_fu_627_p2() {
    and_ln18_2_fu_627_p2 = (select_ln18_3_fu_589_p3.read() & and_ln18_fu_609_p2.read());
}

void hw5_ex1::thread_and_ln18_fu_609_p2() {
    and_ln18_fu_609_p2 = (shl_ln18_1_fu_597_p2.read() & lshr_ln18_fu_603_p2.read());
}

void hw5_ex1::thread_and_ln6_fu_354_p2() {
    and_ln6_fu_354_p2 = (lshr_ln6_fu_342_p2.read() & lshr_ln6_1_fu_348_p2.read());
}

void hw5_ex1::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void hw5_ex1::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void hw5_ex1::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void hw5_ex1::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void hw5_ex1::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void hw5_ex1::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void hw5_ex1::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void hw5_ex1::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void hw5_ex1::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln55_fu_229_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void hw5_ex1::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void hw5_ex1::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln55_fu_229_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void hw5_ex1::thread_empty_11_fu_509_p2() {
    empty_11_fu_509_p2 = (shl_ln_fu_501_p3.read() | ap_const_lv10_1F);
}

void hw5_ex1::thread_empty_8_fu_266_p2() {
    empty_8_fu_266_p2 = (tmp_1_fu_258_p3.read() | ap_const_lv10_1F);
}

void hw5_ex1::thread_i_1_fu_387_p2() {
    i_1_fu_387_p2 = (!i_0_i3_reg_189.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i_0_i3_reg_189.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void hw5_ex1::thread_i_2_fu_235_p2() {
    i_2_fu_235_p2 = (!i_0_reg_167.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i_0_reg_167.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void hw5_ex1::thread_i_3_fu_490_p2() {
    i_3_fu_490_p2 = (!i_0_i5_reg_212.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i_0_i5_reg_212.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void hw5_ex1::thread_i_fu_247_p2() {
    i_fu_247_p2 = (!i_0_i_reg_178.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i_0_i_reg_178.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void hw5_ex1::thread_icmp_ln11_fu_365_p2() {
    icmp_ln11_fu_365_p2 = (!i_0_i3_reg_189.read().is_01() || !ap_const_lv5_1D.is_01())? sc_lv<1>(): sc_lv<1>(i_0_i3_reg_189.read() == ap_const_lv5_1D);
}

void hw5_ex1::thread_icmp_ln17_fu_484_p2() {
    icmp_ln17_fu_484_p2 = (!i_0_i5_reg_212.read().is_01() || !ap_const_lv5_1E.is_01())? sc_lv<1>(): sc_lv<1>(i_0_i5_reg_212.read() == ap_const_lv5_1E);
}

void hw5_ex1::thread_icmp_ln18_fu_515_p2() {
    icmp_ln18_fu_515_p2 = (!shl_ln_fu_501_p3.read().is_01() || !empty_11_fu_509_p2.read().is_01())? sc_lv<1>(): (sc_biguint<10>(shl_ln_fu_501_p3.read()) > sc_biguint<10>(empty_11_fu_509_p2.read()));
}

void hw5_ex1::thread_icmp_ln55_fu_229_p2() {
    icmp_ln55_fu_229_p2 = (!i_0_reg_167.read().is_01() || !ap_const_lv5_1E.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_167.read() == ap_const_lv5_1E);
}

void hw5_ex1::thread_icmp_ln5_fu_241_p2() {
    icmp_ln5_fu_241_p2 = (!i_0_i_reg_178.read().is_01() || !ap_const_lv5_1E.is_01())? sc_lv<1>(): sc_lv<1>(i_0_i_reg_178.read() == ap_const_lv5_1E);
}

void hw5_ex1::thread_icmp_ln6_fu_272_p2() {
    icmp_ln6_fu_272_p2 = (!tmp_1_fu_258_p3.read().is_01() || !empty_8_fu_266_p2.read().is_01())? sc_lv<1>(): (sc_biguint<10>(tmp_1_fu_258_p3.read()) > sc_biguint<10>(empty_8_fu_266_p2.read()));
}

void hw5_ex1::thread_lshr_ln18_fu_603_p2() {
    lshr_ln18_fu_603_p2 = (!zext_ln18_4_fu_569_p1.read().is_01())? sc_lv<960>(): ap_const_lv960_lc_1 >> (unsigned short)zext_ln18_4_fu_569_p1.read().to_uint();
}

void hw5_ex1::thread_lshr_ln6_1_fu_348_p2() {
    lshr_ln6_1_fu_348_p2 = (!zext_ln6_2_fu_338_p1.read().is_01())? sc_lv<960>(): ap_const_lv960_lc_1 >> (unsigned short)zext_ln6_2_fu_338_p1.read().to_uint();
}

void hw5_ex1::thread_lshr_ln6_fu_342_p2() {
    lshr_ln6_fu_342_p2 = (!zext_ln6_1_fu_334_p1.read().is_01())? sc_lv<960>(): select_ln6_1_fu_313_p3.read() >> (unsigned short)zext_ln6_1_fu_334_p1.read().to_uint();
}

void hw5_ex1::thread_mul_ln12_fu_413_p0() {
    mul_ln12_fu_413_p0 = add_ln12_3_fu_404_p2.read();
}

void hw5_ex1::thread_mul_ln12_fu_413_p2() {
    mul_ln12_fu_413_p2 = (!mul_ln12_fu_413_p0.read().is_01() || !ap_const_lv65_155555556.is_01())? sc_lv<65>(): sc_bigint<32>(mul_ln12_fu_413_p0.read()) * sc_biguint<65>(ap_const_lv65_155555556);
}

void hw5_ex1::thread_or_ln18_fu_633_p2() {
    or_ln18_fu_633_p2 = (and_ln18_1_fu_621_p2.read() | and_ln18_2_fu_627_p2.read());
}

void hw5_ex1::thread_select_ln12_1_fu_475_p3() {
    select_ln12_1_fu_475_p3 = (!tmp_5_fu_425_p3.read()[0].is_01())? sc_lv<32>(): ((tmp_5_fu_425_p3.read()[0].to_bool())? sub_ln12_1_fu_469_p2.read(): sext_ln12_2_fu_457_p1.read());
}

void hw5_ex1::thread_select_ln12_fu_461_p3() {
    select_ln12_fu_461_p3 = (!tmp_5_fu_425_p3.read()[0].is_01())? sc_lv<32>(): ((tmp_5_fu_425_p3.read()[0].to_bool())? sext_ln12_1_fu_443_p1.read(): sext_ln12_2_fu_457_p1.read());
}

void hw5_ex1::thread_select_ln18_1_fu_539_p3() {
    select_ln18_1_fu_539_p3 = (!icmp_ln18_fu_515_p2.read()[0].is_01())? sc_lv<10>(): ((icmp_ln18_fu_515_p2.read()[0].to_bool())? empty_11_fu_509_p2.read(): shl_ln_fu_501_p3.read());
}

void hw5_ex1::thread_select_ln18_2_fu_547_p3() {
    select_ln18_2_fu_547_p3 = (!icmp_ln18_fu_515_p2.read()[0].is_01())? sc_lv<10>(): ((icmp_ln18_fu_515_p2.read()[0].to_bool())? sub_ln18_fu_525_p2.read(): shl_ln_fu_501_p3.read());
}

void hw5_ex1::thread_select_ln18_3_fu_589_p3() {
    select_ln18_3_fu_589_p3 = (!icmp_ln18_fu_515_p2.read()[0].is_01())? sc_lv<960>(): ((icmp_ln18_fu_515_p2.read()[0].to_bool())? tmp_8_fu_579_p4.read(): shl_ln18_fu_573_p2.read());
}

void hw5_ex1::thread_select_ln18_fu_531_p3() {
    select_ln18_fu_531_p3 = (!icmp_ln18_fu_515_p2.read()[0].is_01())? sc_lv<10>(): ((icmp_ln18_fu_515_p2.read()[0].to_bool())? shl_ln_fu_501_p3.read(): empty_11_fu_509_p2.read());
}

void hw5_ex1::thread_select_ln6_1_fu_313_p3() {
    select_ln6_1_fu_313_p3 = (!icmp_ln6_fu_272_p2.read()[0].is_01())? sc_lv<960>(): ((icmp_ln6_fu_272_p2.read()[0].to_bool())? tmp_4_fu_278_p4.read(): A.read());
}

void hw5_ex1::thread_select_ln6_2_fu_320_p3() {
    select_ln6_2_fu_320_p3 = (!icmp_ln6_fu_272_p2.read()[0].is_01())? sc_lv<10>(): ((icmp_ln6_fu_272_p2.read()[0].to_bool())? sub_ln6_1_fu_293_p2.read(): tmp_1_fu_258_p3.read());
}

void hw5_ex1::thread_select_ln6_fu_305_p3() {
    select_ln6_fu_305_p3 = (!icmp_ln6_fu_272_p2.read()[0].is_01())? sc_lv<10>(): ((icmp_ln6_fu_272_p2.read()[0].to_bool())? sub_ln6_fu_287_p2.read(): sub_ln6_2_fu_299_p2.read());
}

void hw5_ex1::thread_sext_ln12_1_fu_443_p1() {
    sext_ln12_1_fu_443_p1 = esl_sext<32,31>(tmp_6_fu_433_p4.read());
}

void hw5_ex1::thread_sext_ln12_2_fu_457_p1() {
    sext_ln12_2_fu_457_p1 = esl_sext<32,31>(tmp_7_fu_447_p4.read());
}

void hw5_ex1::thread_shl_ln18_1_fu_597_p2() {
    shl_ln18_1_fu_597_p2 = (!zext_ln18_3_fu_565_p1.read().is_01())? sc_lv<960>(): ap_const_lv960_lc_1 << (unsigned short)zext_ln18_3_fu_565_p1.read().to_uint();
}

void hw5_ex1::thread_shl_ln18_fu_573_p2() {
    shl_ln18_fu_573_p2 = (!zext_ln18_2_fu_561_p1.read().is_01())? sc_lv<960>(): zext_ln18_1_fu_521_p1.read() << (unsigned short)zext_ln18_2_fu_561_p1.read().to_uint();
}

void hw5_ex1::thread_shl_ln_fu_501_p3() {
    shl_ln_fu_501_p3 = esl_concat<5,5>(i_0_i5_reg_212.read(), ap_const_lv5_0);
}

void hw5_ex1::thread_sub_ln12_1_fu_469_p2() {
    sub_ln12_1_fu_469_p2 = (!ap_const_lv32_0.is_01() || !select_ln12_fu_461_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(select_ln12_fu_461_p3.read()));
}

void hw5_ex1::thread_sub_ln12_fu_419_p2() {
    sub_ln12_fu_419_p2 = (!ap_const_lv65_0.is_01() || !mul_ln12_fu_413_p2.read().is_01())? sc_lv<65>(): (sc_biguint<65>(ap_const_lv65_0) - sc_biguint<65>(mul_ln12_fu_413_p2.read()));
}

void hw5_ex1::thread_sub_ln18_1_fu_555_p2() {
    sub_ln18_1_fu_555_p2 = (!ap_const_lv10_3BF.is_01() || !select_ln18_fu_531_p3.read().is_01())? sc_lv<10>(): (sc_bigint<10>(ap_const_lv10_3BF) - sc_biguint<10>(select_ln18_fu_531_p3.read()));
}

void hw5_ex1::thread_sub_ln18_fu_525_p2() {
    sub_ln18_fu_525_p2 = (!ap_const_lv10_3BF.is_01() || !shl_ln_fu_501_p3.read().is_01())? sc_lv<10>(): (sc_bigint<10>(ap_const_lv10_3BF) - sc_biguint<10>(shl_ln_fu_501_p3.read()));
}

void hw5_ex1::thread_sub_ln6_1_fu_293_p2() {
    sub_ln6_1_fu_293_p2 = (!ap_const_lv10_3BF.is_01() || !tmp_1_fu_258_p3.read().is_01())? sc_lv<10>(): (sc_bigint<10>(ap_const_lv10_3BF) - sc_biguint<10>(tmp_1_fu_258_p3.read()));
}

void hw5_ex1::thread_sub_ln6_2_fu_299_p2() {
    sub_ln6_2_fu_299_p2 = (!empty_8_fu_266_p2.read().is_01() || !tmp_1_fu_258_p3.read().is_01())? sc_lv<10>(): (sc_biguint<10>(empty_8_fu_266_p2.read()) - sc_biguint<10>(tmp_1_fu_258_p3.read()));
}

void hw5_ex1::thread_sub_ln6_3_fu_328_p2() {
    sub_ln6_3_fu_328_p2 = (!ap_const_lv10_3BF.is_01() || !select_ln6_fu_305_p3.read().is_01())? sc_lv<10>(): (sc_bigint<10>(ap_const_lv10_3BF) - sc_biguint<10>(select_ln6_fu_305_p3.read()));
}

void hw5_ex1::thread_sub_ln6_fu_287_p2() {
    sub_ln6_fu_287_p2 = (!tmp_1_fu_258_p3.read().is_01() || !empty_8_fu_266_p2.read().is_01())? sc_lv<10>(): (sc_biguint<10>(tmp_1_fu_258_p3.read()) - sc_biguint<10>(empty_8_fu_266_p2.read()));
}

void hw5_ex1::thread_temp1_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        temp1_address0 =  (sc_lv<5>) (zext_ln12_1_fu_382_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        temp1_address0 =  (sc_lv<5>) (zext_ln12_fu_377_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        temp1_address0 =  (sc_lv<5>) (zext_ln6_fu_253_p1.read());
    } else {
        temp1_address0 = "XXXXX";
    }
}

void hw5_ex1::thread_temp1_address1() {
    temp1_address1 =  (sc_lv<5>) (zext_ln12_2_fu_393_p1.read());
}

void hw5_ex1::thread_temp1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        temp1_ce0 = ap_const_logic_1;
    } else {
        temp1_ce0 = ap_const_logic_0;
    }
}

void hw5_ex1::thread_temp1_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        temp1_ce1 = ap_const_logic_1;
    } else {
        temp1_ce1 = ap_const_logic_0;
    }
}

void hw5_ex1::thread_temp1_d0() {
    temp1_d0 = and_ln6_fu_354_p2.read().range(32-1, 0);
}

void hw5_ex1::thread_temp1_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln5_fu_241_p2.read()))) {
        temp1_we0 = ap_const_logic_1;
    } else {
        temp1_we0 = ap_const_logic_0;
    }
}

void hw5_ex1::thread_temp2_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        temp2_address0 =  (sc_lv<5>) (zext_ln18_fu_496_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        temp2_address0 =  (sc_lv<5>) (zext_ln12_1_reg_679.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        temp2_address0 =  (sc_lv<5>) (zext_ln55_fu_224_p1.read());
    } else {
        temp2_address0 = "XXXXX";
    }
}

void hw5_ex1::thread_temp2_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        temp2_ce0 = ap_const_logic_1;
    } else {
        temp2_ce0 = ap_const_logic_0;
    }
}

void hw5_ex1::thread_temp2_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        temp2_d0 = select_ln12_1_fu_475_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        temp2_d0 = ap_const_lv32_0;
    } else {
        temp2_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void hw5_ex1::thread_temp2_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(icmp_ln55_fu_229_p2.read(), ap_const_lv1_0)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        temp2_we0 = ap_const_logic_1;
    } else {
        temp2_we0 = ap_const_logic_0;
    }
}

void hw5_ex1::thread_tmp_1_fu_258_p3() {
    tmp_1_fu_258_p3 = esl_concat<5,5>(i_0_i_reg_178.read(), ap_const_lv5_0);
}

void hw5_ex1::thread_tmp_4_fu_278_p4() {
    tmp_4_fu_278_p4 = A.read().range(0, 959);
}

void hw5_ex1::thread_tmp_5_fu_425_p3() {
    tmp_5_fu_425_p3 = add_ln12_3_fu_404_p2.read().range(31, 31);
}

void hw5_ex1::thread_tmp_6_fu_433_p4() {
    tmp_6_fu_433_p4 = sub_ln12_fu_419_p2.read().range(64, 34);
}

void hw5_ex1::thread_tmp_7_fu_447_p4() {
    tmp_7_fu_447_p4 = mul_ln12_fu_413_p2.read().range(64, 34);
}

void hw5_ex1::thread_tmp_8_fu_579_p4() {
    tmp_8_fu_579_p4 = shl_ln18_fu_573_p2.read().range(0, 959);
}

void hw5_ex1::thread_xor_ln18_fu_615_p2() {
    xor_ln18_fu_615_p2 = (and_ln18_fu_609_p2.read() ^ ap_const_lv960_lc_1);
}

void hw5_ex1::thread_zext_ln12_1_fu_382_p1() {
    zext_ln12_1_fu_382_p1 = esl_zext<64,5>(i_0_i3_reg_189.read());
}

void hw5_ex1::thread_zext_ln12_2_fu_393_p1() {
    zext_ln12_2_fu_393_p1 = esl_zext<64,5>(i_1_fu_387_p2.read());
}

void hw5_ex1::thread_zext_ln12_fu_377_p1() {
    zext_ln12_fu_377_p1 = esl_zext<64,5>(add_ln12_fu_371_p2.read());
}

void hw5_ex1::thread_zext_ln18_1_fu_521_p1() {
    zext_ln18_1_fu_521_p1 = esl_zext<960,32>(temp2_q0.read());
}

void hw5_ex1::thread_zext_ln18_2_fu_561_p1() {
    zext_ln18_2_fu_561_p1 = esl_zext<960,10>(select_ln18_2_fu_547_p3.read());
}

void hw5_ex1::thread_zext_ln18_3_fu_565_p1() {
    zext_ln18_3_fu_565_p1 = esl_zext<960,10>(select_ln18_1_fu_539_p3.read());
}

void hw5_ex1::thread_zext_ln18_4_fu_569_p1() {
    zext_ln18_4_fu_569_p1 = esl_zext<960,10>(sub_ln18_1_fu_555_p2.read());
}

void hw5_ex1::thread_zext_ln18_fu_496_p1() {
    zext_ln18_fu_496_p1 = esl_zext<64,5>(i_0_i5_reg_212.read());
}

void hw5_ex1::thread_zext_ln55_fu_224_p1() {
    zext_ln55_fu_224_p1 = esl_zext<64,5>(i_0_reg_167.read());
}

void hw5_ex1::thread_zext_ln6_1_fu_334_p1() {
    zext_ln6_1_fu_334_p1 = esl_zext<960,10>(select_ln6_2_fu_320_p3.read());
}

void hw5_ex1::thread_zext_ln6_2_fu_338_p1() {
    zext_ln6_2_fu_338_p1 = esl_zext<960,10>(sub_ln6_3_fu_328_p2.read());
}

void hw5_ex1::thread_zext_ln6_fu_253_p1() {
    zext_ln6_fu_253_p1 = esl_zext<64,5>(i_0_i_reg_178.read());
}

void hw5_ex1::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln55_fu_229_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln5_fu_241_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln11_fu_365_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln17_fu_484_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<8>) ("XXXXXXXX");
            break;
    }
}

void hw5_ex1::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"A\" :  \"" << A.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"B_i\" :  \"" << B_i.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"B_o\" :  \"" << B_o.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"B_o_ap_vld\" :  \"" << B_o_ap_vld.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

