-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hw5_ex1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    A : IN STD_LOGIC_VECTOR (959 downto 0);
    B_i : IN STD_LOGIC_VECTOR (959 downto 0);
    B_o : OUT STD_LOGIC_VECTOR (959 downto 0);
    B_o_ap_vld : OUT STD_LOGIC );
end;


architecture behav of hw5_ex1 is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "hw5_ex1,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-flga2104-1-i,HLS_INPUT_CLOCK=25.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.994703,HLS_SYN_LAT=5341,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=4,HLS_SYN_FF=1168,HLS_SYN_LUT=19421,HLS_VERSION=2020_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv5_1E : STD_LOGIC_VECTOR (4 downto 0) := "11110";
    constant ap_const_lv10_1F : STD_LOGIC_VECTOR (9 downto 0) := "0000011111";
    constant ap_const_lv32_3BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001110111111";
    constant ap_const_lv10_3BF : STD_LOGIC_VECTOR (9 downto 0) := "1110111111";
    constant ap_const_lv960_lc_1 : STD_LOGIC_VECTOR (959 downto 0) := "111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv5_1D : STD_LOGIC_VECTOR (4 downto 0) := "11101";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv65_155555556 : STD_LOGIC_VECTOR (64 downto 0) := "00000000000000000000000000000000101010101010101010101010101010110";
    constant ap_const_lv65_0 : STD_LOGIC_VECTOR (64 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_22 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100010";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal i_2_fu_235_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal i_2_reg_642 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln55_fu_229_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_fu_247_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln11_fu_365_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal temp1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal temp1_load_reg_674 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal zext_ln12_1_fu_382_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln12_1_reg_679 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_1_fu_387_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal i_1_reg_689 : STD_LOGIC_VECTOR (4 downto 0);
    signal i_3_fu_490_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal i_3_reg_702 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal icmp_ln17_fu_484_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln18_fu_633_p2 : STD_LOGIC_VECTOR (959 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal temp1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal temp1_ce0 : STD_LOGIC;
    signal temp1_we0 : STD_LOGIC;
    signal temp1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal temp1_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal temp1_ce1 : STD_LOGIC;
    signal temp1_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal temp2_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal temp2_ce0 : STD_LOGIC;
    signal temp2_we0 : STD_LOGIC;
    signal temp2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal temp2_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_0_reg_167 : STD_LOGIC_VECTOR (4 downto 0);
    signal i_0_i_reg_178 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln5_fu_241_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_0_i3_reg_189 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal out_w_0_i_reg_201 : STD_LOGIC_VECTOR (959 downto 0);
    signal i_0_i5_reg_212 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln55_fu_224_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln6_fu_253_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln12_fu_377_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln12_2_fu_393_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln18_fu_496_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln12_1_fu_475_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_258_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal empty_8_fu_266_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln6_fu_272_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln6_fu_287_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln6_2_fu_299_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_4_fu_278_p4 : STD_LOGIC_VECTOR (959 downto 0);
    signal sub_ln6_1_fu_293_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln6_fu_305_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln6_2_fu_320_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln6_3_fu_328_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln6_1_fu_313_p3 : STD_LOGIC_VECTOR (959 downto 0);
    signal zext_ln6_1_fu_334_p1 : STD_LOGIC_VECTOR (959 downto 0);
    signal zext_ln6_2_fu_338_p1 : STD_LOGIC_VECTOR (959 downto 0);
    signal lshr_ln6_fu_342_p2 : STD_LOGIC_VECTOR (959 downto 0);
    signal lshr_ln6_1_fu_348_p2 : STD_LOGIC_VECTOR (959 downto 0);
    signal and_ln6_fu_354_p2 : STD_LOGIC_VECTOR (959 downto 0);
    signal add_ln12_fu_371_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln12_2_fu_398_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln12_3_fu_404_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln12_fu_413_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln12_fu_413_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal sub_ln12_fu_419_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal tmp_6_fu_433_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_7_fu_447_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_5_fu_425_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln12_1_fu_443_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln12_2_fu_457_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln12_fu_461_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln12_1_fu_469_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln_fu_501_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal empty_11_fu_509_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln18_fu_515_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln18_fu_525_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln18_fu_531_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln18_2_fu_547_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln18_1_fu_539_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln18_1_fu_555_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln18_1_fu_521_p1 : STD_LOGIC_VECTOR (959 downto 0);
    signal zext_ln18_2_fu_561_p1 : STD_LOGIC_VECTOR (959 downto 0);
    signal shl_ln18_fu_573_p2 : STD_LOGIC_VECTOR (959 downto 0);
    signal tmp_8_fu_579_p4 : STD_LOGIC_VECTOR (959 downto 0);
    signal zext_ln18_3_fu_565_p1 : STD_LOGIC_VECTOR (959 downto 0);
    signal zext_ln18_4_fu_569_p1 : STD_LOGIC_VECTOR (959 downto 0);
    signal shl_ln18_1_fu_597_p2 : STD_LOGIC_VECTOR (959 downto 0);
    signal lshr_ln18_fu_603_p2 : STD_LOGIC_VECTOR (959 downto 0);
    signal and_ln18_fu_609_p2 : STD_LOGIC_VECTOR (959 downto 0);
    signal xor_ln18_fu_615_p2 : STD_LOGIC_VECTOR (959 downto 0);
    signal select_ln18_3_fu_589_p3 : STD_LOGIC_VECTOR (959 downto 0);
    signal and_ln18_1_fu_621_p2 : STD_LOGIC_VECTOR (959 downto 0);
    signal and_ln18_2_fu_627_p2 : STD_LOGIC_VECTOR (959 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);

    component hw5_ex1_temp1 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component hw5_ex1_temp2 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    temp1_U : component hw5_ex1_temp1
    generic map (
        DataWidth => 32,
        AddressRange => 30,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => temp1_address0,
        ce0 => temp1_ce0,
        we0 => temp1_we0,
        d0 => temp1_d0,
        q0 => temp1_q0,
        address1 => temp1_address1,
        ce1 => temp1_ce1,
        q1 => temp1_q1);

    temp2_U : component hw5_ex1_temp2
    generic map (
        DataWidth => 32,
        AddressRange => 30,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => temp2_address0,
        ce0 => temp2_ce0,
        we0 => temp2_we0,
        d0 => temp2_d0,
        q0 => temp2_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    i_0_i3_reg_189_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln5_fu_241_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                i_0_i3_reg_189 <= ap_const_lv5_1;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                i_0_i3_reg_189 <= i_1_reg_689;
            end if; 
        end if;
    end process;

    i_0_i5_reg_212_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                i_0_i5_reg_212 <= i_3_reg_702;
            elsif (((icmp_ln11_fu_365_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                i_0_i5_reg_212 <= ap_const_lv5_0;
            end if; 
        end if;
    end process;

    i_0_i_reg_178_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln5_fu_241_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                i_0_i_reg_178 <= i_fu_247_p2;
            elsif (((icmp_ln55_fu_229_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                i_0_i_reg_178 <= ap_const_lv5_0;
            end if; 
        end if;
    end process;

    i_0_reg_167_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln17_fu_484_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                i_0_reg_167 <= i_2_reg_642;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_0_reg_167 <= ap_const_lv5_0;
            end if; 
        end if;
    end process;

    out_w_0_i_reg_201_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                out_w_0_i_reg_201 <= or_ln18_fu_633_p2;
            elsif (((icmp_ln11_fu_365_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                out_w_0_i_reg_201 <= B_i;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                i_1_reg_689 <= i_1_fu_387_p2;
                temp1_load_reg_674 <= temp1_q0;
                    zext_ln12_1_reg_679(4 downto 0) <= zext_ln12_1_fu_382_p1(4 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                i_2_reg_642 <= i_2_fu_235_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                i_3_reg_702 <= i_3_fu_490_p2;
            end if;
        end if;
    end process;
    zext_ln12_1_reg_679(63 downto 5) <= "00000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln55_fu_229_p2, ap_CS_fsm_state3, ap_CS_fsm_state4, icmp_ln11_fu_365_p2, ap_CS_fsm_state7, icmp_ln17_fu_484_p2, icmp_ln5_fu_241_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln55_fu_229_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln5_fu_241_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((icmp_ln11_fu_365_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state7 => 
                if (((icmp_ln17_fu_484_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;

    B_o_assign_proc : process(B_i, ap_CS_fsm_state7, icmp_ln17_fu_484_p2, out_w_0_i_reg_201)
    begin
        if (((icmp_ln17_fu_484_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            B_o <= out_w_0_i_reg_201;
        else 
            B_o <= B_i;
        end if; 
    end process;


    B_o_ap_vld_assign_proc : process(ap_CS_fsm_state7, icmp_ln17_fu_484_p2)
    begin
        if (((icmp_ln17_fu_484_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            B_o_ap_vld <= ap_const_logic_1;
        else 
            B_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln12_2_fu_398_p2 <= std_logic_vector(unsigned(temp1_q0) + unsigned(temp1_q1));
    add_ln12_3_fu_404_p2 <= std_logic_vector(unsigned(add_ln12_2_fu_398_p2) + unsigned(temp1_load_reg_674));
    add_ln12_fu_371_p2 <= std_logic_vector(unsigned(i_0_i3_reg_189) + unsigned(ap_const_lv5_1F));
    and_ln18_1_fu_621_p2 <= (xor_ln18_fu_615_p2 and out_w_0_i_reg_201);
    and_ln18_2_fu_627_p2 <= (select_ln18_3_fu_589_p3 and and_ln18_fu_609_p2);
    and_ln18_fu_609_p2 <= (shl_ln18_1_fu_597_p2 and lshr_ln18_fu_603_p2);
    and_ln6_fu_354_p2 <= (lshr_ln6_fu_342_p2 and lshr_ln6_1_fu_348_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);

    ap_done_assign_proc : process(ap_CS_fsm_state2, icmp_ln55_fu_229_p2)
    begin
        if (((icmp_ln55_fu_229_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln55_fu_229_p2)
    begin
        if (((icmp_ln55_fu_229_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    empty_11_fu_509_p2 <= (shl_ln_fu_501_p3 or ap_const_lv10_1F);
    empty_8_fu_266_p2 <= (tmp_1_fu_258_p3 or ap_const_lv10_1F);
    i_1_fu_387_p2 <= std_logic_vector(unsigned(i_0_i3_reg_189) + unsigned(ap_const_lv5_1));
    i_2_fu_235_p2 <= std_logic_vector(unsigned(i_0_reg_167) + unsigned(ap_const_lv5_1));
    i_3_fu_490_p2 <= std_logic_vector(unsigned(i_0_i5_reg_212) + unsigned(ap_const_lv5_1));
    i_fu_247_p2 <= std_logic_vector(unsigned(i_0_i_reg_178) + unsigned(ap_const_lv5_1));
    icmp_ln11_fu_365_p2 <= "1" when (i_0_i3_reg_189 = ap_const_lv5_1D) else "0";
    icmp_ln17_fu_484_p2 <= "1" when (i_0_i5_reg_212 = ap_const_lv5_1E) else "0";
    icmp_ln18_fu_515_p2 <= "1" when (unsigned(shl_ln_fu_501_p3) > unsigned(empty_11_fu_509_p2)) else "0";
    icmp_ln55_fu_229_p2 <= "1" when (i_0_reg_167 = ap_const_lv5_1E) else "0";
    icmp_ln5_fu_241_p2 <= "1" when (i_0_i_reg_178 = ap_const_lv5_1E) else "0";
    icmp_ln6_fu_272_p2 <= "1" when (unsigned(tmp_1_fu_258_p3) > unsigned(empty_8_fu_266_p2)) else "0";
    lshr_ln18_fu_603_p2 <= std_logic_vector(shift_right(unsigned(ap_const_lv960_lc_1),to_integer(unsigned('0' & zext_ln18_4_fu_569_p1(31-1 downto 0)))));
    lshr_ln6_1_fu_348_p2 <= std_logic_vector(shift_right(unsigned(ap_const_lv960_lc_1),to_integer(unsigned('0' & zext_ln6_2_fu_338_p1(31-1 downto 0)))));
    lshr_ln6_fu_342_p2 <= std_logic_vector(shift_right(unsigned(select_ln6_1_fu_313_p3),to_integer(unsigned('0' & zext_ln6_1_fu_334_p1(31-1 downto 0)))));
    mul_ln12_fu_413_p0 <= add_ln12_3_fu_404_p2;
    mul_ln12_fu_413_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln12_fu_413_p0) * signed('0' &ap_const_lv65_155555556))), 65));
    or_ln18_fu_633_p2 <= (and_ln18_2_fu_627_p2 or and_ln18_1_fu_621_p2);
    select_ln12_1_fu_475_p3 <= 
        sub_ln12_1_fu_469_p2 when (tmp_5_fu_425_p3(0) = '1') else 
        sext_ln12_2_fu_457_p1;
    select_ln12_fu_461_p3 <= 
        sext_ln12_1_fu_443_p1 when (tmp_5_fu_425_p3(0) = '1') else 
        sext_ln12_2_fu_457_p1;
    select_ln18_1_fu_539_p3 <= 
        empty_11_fu_509_p2 when (icmp_ln18_fu_515_p2(0) = '1') else 
        shl_ln_fu_501_p3;
    select_ln18_2_fu_547_p3 <= 
        sub_ln18_fu_525_p2 when (icmp_ln18_fu_515_p2(0) = '1') else 
        shl_ln_fu_501_p3;
    select_ln18_3_fu_589_p3 <= 
        tmp_8_fu_579_p4 when (icmp_ln18_fu_515_p2(0) = '1') else 
        shl_ln18_fu_573_p2;
    select_ln18_fu_531_p3 <= 
        shl_ln_fu_501_p3 when (icmp_ln18_fu_515_p2(0) = '1') else 
        empty_11_fu_509_p2;
    select_ln6_1_fu_313_p3 <= 
        tmp_4_fu_278_p4 when (icmp_ln6_fu_272_p2(0) = '1') else 
        A;
    select_ln6_2_fu_320_p3 <= 
        sub_ln6_1_fu_293_p2 when (icmp_ln6_fu_272_p2(0) = '1') else 
        tmp_1_fu_258_p3;
    select_ln6_fu_305_p3 <= 
        sub_ln6_fu_287_p2 when (icmp_ln6_fu_272_p2(0) = '1') else 
        sub_ln6_2_fu_299_p2;
        sext_ln12_1_fu_443_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_6_fu_433_p4),32));

        sext_ln12_2_fu_457_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_7_fu_447_p4),32));

    shl_ln18_1_fu_597_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv960_lc_1),to_integer(unsigned('0' & zext_ln18_3_fu_565_p1(31-1 downto 0)))));
    shl_ln18_fu_573_p2 <= std_logic_vector(shift_left(unsigned(zext_ln18_1_fu_521_p1),to_integer(unsigned('0' & zext_ln18_2_fu_561_p1(31-1 downto 0)))));
    shl_ln_fu_501_p3 <= (i_0_i5_reg_212 & ap_const_lv5_0);
    sub_ln12_1_fu_469_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(select_ln12_fu_461_p3));
    sub_ln12_fu_419_p2 <= std_logic_vector(unsigned(ap_const_lv65_0) - unsigned(mul_ln12_fu_413_p2));
    sub_ln18_1_fu_555_p2 <= std_logic_vector(signed(ap_const_lv10_3BF) - signed(select_ln18_fu_531_p3));
    sub_ln18_fu_525_p2 <= std_logic_vector(signed(ap_const_lv10_3BF) - signed(shl_ln_fu_501_p3));
    sub_ln6_1_fu_293_p2 <= std_logic_vector(signed(ap_const_lv10_3BF) - signed(tmp_1_fu_258_p3));
    sub_ln6_2_fu_299_p2 <= std_logic_vector(unsigned(empty_8_fu_266_p2) - unsigned(tmp_1_fu_258_p3));
    sub_ln6_3_fu_328_p2 <= std_logic_vector(signed(ap_const_lv10_3BF) - signed(select_ln6_fu_305_p3));
    sub_ln6_fu_287_p2 <= std_logic_vector(unsigned(tmp_1_fu_258_p3) - unsigned(empty_8_fu_266_p2));

    temp1_address0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, zext_ln12_1_fu_382_p1, zext_ln6_fu_253_p1, zext_ln12_fu_377_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            temp1_address0 <= zext_ln12_1_fu_382_p1(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            temp1_address0 <= zext_ln12_fu_377_p1(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            temp1_address0 <= zext_ln6_fu_253_p1(5 - 1 downto 0);
        else 
            temp1_address0 <= "XXXXX";
        end if; 
    end process;

    temp1_address1 <= zext_ln12_2_fu_393_p1(5 - 1 downto 0);

    temp1_ce0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            temp1_ce0 <= ap_const_logic_1;
        else 
            temp1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    temp1_ce1_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            temp1_ce1 <= ap_const_logic_1;
        else 
            temp1_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    temp1_d0 <= and_ln6_fu_354_p2(32 - 1 downto 0);

    temp1_we0_assign_proc : process(ap_CS_fsm_state3, icmp_ln5_fu_241_p2)
    begin
        if (((icmp_ln5_fu_241_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            temp1_we0 <= ap_const_logic_1;
        else 
            temp1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    temp2_address0_assign_proc : process(ap_CS_fsm_state2, zext_ln12_1_reg_679, ap_CS_fsm_state7, ap_CS_fsm_state6, zext_ln55_fu_224_p1, zext_ln18_fu_496_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            temp2_address0 <= zext_ln18_fu_496_p1(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            temp2_address0 <= zext_ln12_1_reg_679(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            temp2_address0 <= zext_ln55_fu_224_p1(5 - 1 downto 0);
        else 
            temp2_address0 <= "XXXXX";
        end if; 
    end process;


    temp2_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state7, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            temp2_ce0 <= ap_const_logic_1;
        else 
            temp2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    temp2_d0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state6, select_ln12_1_fu_475_p3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            temp2_d0 <= select_ln12_1_fu_475_p3;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            temp2_d0 <= ap_const_lv32_0;
        else 
            temp2_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    temp2_we0_assign_proc : process(ap_CS_fsm_state2, icmp_ln55_fu_229_p2, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or ((icmp_ln55_fu_229_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            temp2_we0 <= ap_const_logic_1;
        else 
            temp2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    tmp_1_fu_258_p3 <= (i_0_i_reg_178 & ap_const_lv5_0);
    
    tmp_4_fu_278_p4_proc : process(A)
    variable vlo_cpy : STD_LOGIC_VECTOR(960+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(960+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(960 - 1 downto 0);
    variable tmp_4_fu_278_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(960 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(960 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(960 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(10 - 1 downto 0) := ap_const_lv32_3BF(10 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(10 - 1 downto 0) := ap_const_lv32_0(10 - 1 downto 0);
        v0_cpy := A;
        if (vlo_cpy(10 - 1 downto 0) > vhi_cpy(10 - 1 downto 0)) then
            vhi_cpy(10-1 downto 0) := std_logic_vector(960-1-unsigned(ap_const_lv32_0(10-1 downto 0)));
            vlo_cpy(10-1 downto 0) := std_logic_vector(960-1-unsigned(ap_const_lv32_3BF(10-1 downto 0)));
            for tmp_4_fu_278_p4_i in 0 to 960-1 loop
                v0_cpy(tmp_4_fu_278_p4_i) := A(960-1-tmp_4_fu_278_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(10-1 downto 0)))));

        section := (others=>'0');
        section(10-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(10-1 downto 0)) - unsigned(vlo_cpy(10-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(960-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_4_fu_278_p4 <= resvalue(960-1 downto 0);
    end process;

    tmp_5_fu_425_p3 <= add_ln12_3_fu_404_p2(31 downto 31);
    tmp_6_fu_433_p4 <= sub_ln12_fu_419_p2(64 downto 34);
    tmp_7_fu_447_p4 <= mul_ln12_fu_413_p2(64 downto 34);
    
    tmp_8_fu_579_p4_proc : process(shl_ln18_fu_573_p2)
    variable vlo_cpy : STD_LOGIC_VECTOR(960+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(960+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(960 - 1 downto 0);
    variable tmp_8_fu_579_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(960 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(960 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(960 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(10 - 1 downto 0) := ap_const_lv32_3BF(10 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(10 - 1 downto 0) := ap_const_lv32_0(10 - 1 downto 0);
        v0_cpy := shl_ln18_fu_573_p2;
        if (vlo_cpy(10 - 1 downto 0) > vhi_cpy(10 - 1 downto 0)) then
            vhi_cpy(10-1 downto 0) := std_logic_vector(960-1-unsigned(ap_const_lv32_0(10-1 downto 0)));
            vlo_cpy(10-1 downto 0) := std_logic_vector(960-1-unsigned(ap_const_lv32_3BF(10-1 downto 0)));
            for tmp_8_fu_579_p4_i in 0 to 960-1 loop
                v0_cpy(tmp_8_fu_579_p4_i) := shl_ln18_fu_573_p2(960-1-tmp_8_fu_579_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(10-1 downto 0)))));

        section := (others=>'0');
        section(10-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(10-1 downto 0)) - unsigned(vlo_cpy(10-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(960-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_8_fu_579_p4 <= resvalue(960-1 downto 0);
    end process;

    xor_ln18_fu_615_p2 <= (ap_const_lv960_lc_1 xor and_ln18_fu_609_p2);
    zext_ln12_1_fu_382_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_0_i3_reg_189),64));
    zext_ln12_2_fu_393_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_1_fu_387_p2),64));
    zext_ln12_fu_377_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln12_fu_371_p2),64));
    zext_ln18_1_fu_521_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(temp2_q0),960));
    zext_ln18_2_fu_561_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln18_2_fu_547_p3),960));
    zext_ln18_3_fu_565_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln18_1_fu_539_p3),960));
    zext_ln18_4_fu_569_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln18_1_fu_555_p2),960));
    zext_ln18_fu_496_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_0_i5_reg_212),64));
    zext_ln55_fu_224_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_0_reg_167),64));
    zext_ln6_1_fu_334_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln6_2_fu_320_p3),960));
    zext_ln6_2_fu_338_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln6_3_fu_328_p2),960));
    zext_ln6_fu_253_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_0_i_reg_178),64));
end behav;
