// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "neural_net.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic neural_net::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic neural_net::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<6> neural_net::ap_ST_fsm_state1 = "1";
const sc_lv<6> neural_net::ap_ST_fsm_state2 = "10";
const sc_lv<6> neural_net::ap_ST_fsm_state3 = "100";
const sc_lv<6> neural_net::ap_ST_fsm_state4 = "1000";
const sc_lv<6> neural_net::ap_ST_fsm_state5 = "10000";
const sc_lv<6> neural_net::ap_ST_fsm_state6 = "100000";
const sc_lv<32> neural_net::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> neural_net::ap_const_lv32_1 = "1";
const sc_lv<32> neural_net::ap_const_lv32_2 = "10";
const sc_lv<1> neural_net::ap_const_lv1_0 = "0";
const sc_lv<32> neural_net::ap_const_lv32_3 = "11";
const sc_lv<32> neural_net::ap_const_lv32_4 = "100";
const sc_lv<3> neural_net::ap_const_lv3_0 = "000";
const sc_lv<1> neural_net::ap_const_lv1_1 = "1";
const sc_lv<32> neural_net::ap_const_lv32_5 = "101";
const sc_lv<4> neural_net::ap_const_lv4_0 = "0000";
const sc_lv<64> neural_net::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<3> neural_net::ap_const_lv3_6 = "110";
const sc_lv<3> neural_net::ap_const_lv3_5 = "101";
const sc_lv<3> neural_net::ap_const_lv3_4 = "100";
const sc_lv<3> neural_net::ap_const_lv3_3 = "11";
const sc_lv<3> neural_net::ap_const_lv3_2 = "10";
const sc_lv<3> neural_net::ap_const_lv3_1 = "1";
const sc_lv<3> neural_net::ap_const_lv3_7 = "111";
const sc_lv<4> neural_net::ap_const_lv4_8 = "1000";
const sc_lv<4> neural_net::ap_const_lv4_1 = "1";
const bool neural_net::ap_const_boolean_1 = true;

neural_net::neural_net(sc_module_name name) : sc_module(name), mVcdFile(0) {
    neural_net_mux_63bkb_U1 = new neural_net_mux_63bkb<1,1,32,32,32,32,32,32,3,32>("neural_net_mux_63bkb_U1");
    neural_net_mux_63bkb_U1->din0(in_0_q0);
    neural_net_mux_63bkb_U1->din1(in_1_q0);
    neural_net_mux_63bkb_U1->din2(in_2_q0);
    neural_net_mux_63bkb_U1->din3(in_3_q0);
    neural_net_mux_63bkb_U1->din4(in_4_q0);
    neural_net_mux_63bkb_U1->din5(in_5_q0);
    neural_net_mux_63bkb_U1->din6(k_0_reg_412);
    neural_net_mux_63bkb_U1->dout(tmp_fu_476_p8);
    neural_net_mux_83cud_U2 = new neural_net_mux_83cud<1,1,32,32,32,32,32,32,32,32,3,32>("neural_net_mux_83cud_U2");
    neural_net_mux_83cud_U2->din0(weight_0_q0);
    neural_net_mux_83cud_U2->din1(weight_1_q0);
    neural_net_mux_83cud_U2->din2(weight_2_q0);
    neural_net_mux_83cud_U2->din3(weight_3_q0);
    neural_net_mux_83cud_U2->din4(weight_4_q0);
    neural_net_mux_83cud_U2->din5(weight_5_q0);
    neural_net_mux_83cud_U2->din6(weight_6_q0);
    neural_net_mux_83cud_U2->din7(weight_7_q0);
    neural_net_mux_83cud_U2->din8(trunc_ln66_reg_613);
    neural_net_mux_83cud_U2->dout(tmp_1_fu_494_p10);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln52_fu_424_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln52_fu_424_p2 );

    SC_METHOD(thread_i_fu_430_p2);
    sensitive << ( i_0_reg_370 );

    SC_METHOD(thread_icmp_ln52_fu_424_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_370 );

    SC_METHOD(thread_icmp_ln53_fu_436_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( j_0_reg_381 );

    SC_METHOD(thread_icmp_ln55_fu_452_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( k_0_reg_412 );

    SC_METHOD(thread_in_0_address0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_in_0_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_in_1_address0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_in_1_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_in_2_address0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_in_2_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_in_3_address0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_in_3_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_in_4_address0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_in_4_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_in_5_address0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_in_5_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_j_fu_442_p2);
    sensitive << ( j_0_reg_381 );

    SC_METHOD(thread_k_fu_458_p2);
    sensitive << ( k_0_reg_412 );

    SC_METHOD(thread_mul_ln66_fu_515_p2);
    sensitive << ( tmp_fu_476_p8 );
    sensitive << ( tmp_1_fu_494_p10 );

    SC_METHOD(thread_out_0_address0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_out_0_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_out_0_d0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( sum_0_reg_392 );

    SC_METHOD(thread_out_0_we0);
    sensitive << ( trunc_ln66_reg_613 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln55_fu_452_p2 );

    SC_METHOD(thread_out_1_address0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_out_1_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_out_1_d0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( sum_0_reg_392 );

    SC_METHOD(thread_out_1_we0);
    sensitive << ( trunc_ln66_reg_613 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln55_fu_452_p2 );

    SC_METHOD(thread_out_2_address0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_out_2_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_out_2_d0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( sum_0_reg_392 );

    SC_METHOD(thread_out_2_we0);
    sensitive << ( trunc_ln66_reg_613 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln55_fu_452_p2 );

    SC_METHOD(thread_out_3_address0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_out_3_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_out_3_d0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( sum_0_reg_392 );

    SC_METHOD(thread_out_3_we0);
    sensitive << ( trunc_ln66_reg_613 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln55_fu_452_p2 );

    SC_METHOD(thread_out_4_address0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_out_4_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_out_4_d0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( sum_0_reg_392 );

    SC_METHOD(thread_out_4_we0);
    sensitive << ( trunc_ln66_reg_613 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln55_fu_452_p2 );

    SC_METHOD(thread_out_5_address0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_out_5_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_out_5_d0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( sum_0_reg_392 );

    SC_METHOD(thread_out_5_we0);
    sensitive << ( trunc_ln66_reg_613 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln55_fu_452_p2 );

    SC_METHOD(thread_out_6_address0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_out_6_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_out_6_d0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( sum_0_reg_392 );

    SC_METHOD(thread_out_6_we0);
    sensitive << ( trunc_ln66_reg_613 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln55_fu_452_p2 );

    SC_METHOD(thread_out_7_address0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_out_7_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_out_7_d0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( sum_0_reg_392 );

    SC_METHOD(thread_out_7_we0);
    sensitive << ( trunc_ln66_reg_613 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln55_fu_452_p2 );

    SC_METHOD(thread_sum_fu_521_p2);
    sensitive << ( sum_0_reg_392 );
    sensitive << ( mul_ln66_fu_515_p2 );

    SC_METHOD(thread_trunc_ln66_fu_448_p1);
    sensitive << ( j_0_reg_381 );

    SC_METHOD(thread_weight_0_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( zext_ln66_fu_464_p1 );

    SC_METHOD(thread_weight_0_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_weight_1_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( zext_ln66_fu_464_p1 );

    SC_METHOD(thread_weight_1_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_weight_2_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( zext_ln66_fu_464_p1 );

    SC_METHOD(thread_weight_2_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_weight_3_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( zext_ln66_fu_464_p1 );

    SC_METHOD(thread_weight_3_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_weight_4_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( zext_ln66_fu_464_p1 );

    SC_METHOD(thread_weight_4_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_weight_5_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( zext_ln66_fu_464_p1 );

    SC_METHOD(thread_weight_5_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_weight_6_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( zext_ln66_fu_464_p1 );

    SC_METHOD(thread_weight_6_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_weight_7_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( zext_ln66_fu_464_p1 );

    SC_METHOD(thread_weight_7_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_zext_ln66_fu_464_p1);
    sensitive << ( k_0_reg_412 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln53_fu_436_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln55_fu_452_p2 );
    sensitive << ( icmp_ln52_fu_424_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "neural_net_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, in_0_address0, "(port)in_0_address0");
    sc_trace(mVcdFile, in_0_ce0, "(port)in_0_ce0");
    sc_trace(mVcdFile, in_0_q0, "(port)in_0_q0");
    sc_trace(mVcdFile, in_1_address0, "(port)in_1_address0");
    sc_trace(mVcdFile, in_1_ce0, "(port)in_1_ce0");
    sc_trace(mVcdFile, in_1_q0, "(port)in_1_q0");
    sc_trace(mVcdFile, in_2_address0, "(port)in_2_address0");
    sc_trace(mVcdFile, in_2_ce0, "(port)in_2_ce0");
    sc_trace(mVcdFile, in_2_q0, "(port)in_2_q0");
    sc_trace(mVcdFile, in_3_address0, "(port)in_3_address0");
    sc_trace(mVcdFile, in_3_ce0, "(port)in_3_ce0");
    sc_trace(mVcdFile, in_3_q0, "(port)in_3_q0");
    sc_trace(mVcdFile, in_4_address0, "(port)in_4_address0");
    sc_trace(mVcdFile, in_4_ce0, "(port)in_4_ce0");
    sc_trace(mVcdFile, in_4_q0, "(port)in_4_q0");
    sc_trace(mVcdFile, in_5_address0, "(port)in_5_address0");
    sc_trace(mVcdFile, in_5_ce0, "(port)in_5_ce0");
    sc_trace(mVcdFile, in_5_q0, "(port)in_5_q0");
    sc_trace(mVcdFile, out_0_address0, "(port)out_0_address0");
    sc_trace(mVcdFile, out_0_ce0, "(port)out_0_ce0");
    sc_trace(mVcdFile, out_0_we0, "(port)out_0_we0");
    sc_trace(mVcdFile, out_0_d0, "(port)out_0_d0");
    sc_trace(mVcdFile, out_1_address0, "(port)out_1_address0");
    sc_trace(mVcdFile, out_1_ce0, "(port)out_1_ce0");
    sc_trace(mVcdFile, out_1_we0, "(port)out_1_we0");
    sc_trace(mVcdFile, out_1_d0, "(port)out_1_d0");
    sc_trace(mVcdFile, out_2_address0, "(port)out_2_address0");
    sc_trace(mVcdFile, out_2_ce0, "(port)out_2_ce0");
    sc_trace(mVcdFile, out_2_we0, "(port)out_2_we0");
    sc_trace(mVcdFile, out_2_d0, "(port)out_2_d0");
    sc_trace(mVcdFile, out_3_address0, "(port)out_3_address0");
    sc_trace(mVcdFile, out_3_ce0, "(port)out_3_ce0");
    sc_trace(mVcdFile, out_3_we0, "(port)out_3_we0");
    sc_trace(mVcdFile, out_3_d0, "(port)out_3_d0");
    sc_trace(mVcdFile, out_4_address0, "(port)out_4_address0");
    sc_trace(mVcdFile, out_4_ce0, "(port)out_4_ce0");
    sc_trace(mVcdFile, out_4_we0, "(port)out_4_we0");
    sc_trace(mVcdFile, out_4_d0, "(port)out_4_d0");
    sc_trace(mVcdFile, out_5_address0, "(port)out_5_address0");
    sc_trace(mVcdFile, out_5_ce0, "(port)out_5_ce0");
    sc_trace(mVcdFile, out_5_we0, "(port)out_5_we0");
    sc_trace(mVcdFile, out_5_d0, "(port)out_5_d0");
    sc_trace(mVcdFile, out_6_address0, "(port)out_6_address0");
    sc_trace(mVcdFile, out_6_ce0, "(port)out_6_ce0");
    sc_trace(mVcdFile, out_6_we0, "(port)out_6_we0");
    sc_trace(mVcdFile, out_6_d0, "(port)out_6_d0");
    sc_trace(mVcdFile, out_7_address0, "(port)out_7_address0");
    sc_trace(mVcdFile, out_7_ce0, "(port)out_7_ce0");
    sc_trace(mVcdFile, out_7_we0, "(port)out_7_we0");
    sc_trace(mVcdFile, out_7_d0, "(port)out_7_d0");
    sc_trace(mVcdFile, weight_0_address0, "(port)weight_0_address0");
    sc_trace(mVcdFile, weight_0_ce0, "(port)weight_0_ce0");
    sc_trace(mVcdFile, weight_0_q0, "(port)weight_0_q0");
    sc_trace(mVcdFile, weight_1_address0, "(port)weight_1_address0");
    sc_trace(mVcdFile, weight_1_ce0, "(port)weight_1_ce0");
    sc_trace(mVcdFile, weight_1_q0, "(port)weight_1_q0");
    sc_trace(mVcdFile, weight_2_address0, "(port)weight_2_address0");
    sc_trace(mVcdFile, weight_2_ce0, "(port)weight_2_ce0");
    sc_trace(mVcdFile, weight_2_q0, "(port)weight_2_q0");
    sc_trace(mVcdFile, weight_3_address0, "(port)weight_3_address0");
    sc_trace(mVcdFile, weight_3_ce0, "(port)weight_3_ce0");
    sc_trace(mVcdFile, weight_3_q0, "(port)weight_3_q0");
    sc_trace(mVcdFile, weight_4_address0, "(port)weight_4_address0");
    sc_trace(mVcdFile, weight_4_ce0, "(port)weight_4_ce0");
    sc_trace(mVcdFile, weight_4_q0, "(port)weight_4_q0");
    sc_trace(mVcdFile, weight_5_address0, "(port)weight_5_address0");
    sc_trace(mVcdFile, weight_5_ce0, "(port)weight_5_ce0");
    sc_trace(mVcdFile, weight_5_q0, "(port)weight_5_q0");
    sc_trace(mVcdFile, weight_6_address0, "(port)weight_6_address0");
    sc_trace(mVcdFile, weight_6_ce0, "(port)weight_6_ce0");
    sc_trace(mVcdFile, weight_6_q0, "(port)weight_6_q0");
    sc_trace(mVcdFile, weight_7_address0, "(port)weight_7_address0");
    sc_trace(mVcdFile, weight_7_ce0, "(port)weight_7_ce0");
    sc_trace(mVcdFile, weight_7_q0, "(port)weight_7_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, i_fu_430_p2, "i_fu_430_p2");
    sc_trace(mVcdFile, i_reg_600, "i_reg_600");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, j_fu_442_p2, "j_fu_442_p2");
    sc_trace(mVcdFile, j_reg_608, "j_reg_608");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, trunc_ln66_fu_448_p1, "trunc_ln66_fu_448_p1");
    sc_trace(mVcdFile, trunc_ln66_reg_613, "trunc_ln66_reg_613");
    sc_trace(mVcdFile, icmp_ln53_fu_436_p2, "icmp_ln53_fu_436_p2");
    sc_trace(mVcdFile, k_fu_458_p2, "k_fu_458_p2");
    sc_trace(mVcdFile, k_reg_621, "k_reg_621");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, icmp_ln55_fu_452_p2, "icmp_ln55_fu_452_p2");
    sc_trace(mVcdFile, sum_fu_521_p2, "sum_fu_521_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, i_0_reg_370, "i_0_reg_370");
    sc_trace(mVcdFile, j_0_reg_381, "j_0_reg_381");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, icmp_ln52_fu_424_p2, "icmp_ln52_fu_424_p2");
    sc_trace(mVcdFile, sum_0_reg_392, "sum_0_reg_392");
    sc_trace(mVcdFile, k_0_reg_412, "k_0_reg_412");
    sc_trace(mVcdFile, zext_ln66_fu_464_p1, "zext_ln66_fu_464_p1");
    sc_trace(mVcdFile, tmp_fu_476_p8, "tmp_fu_476_p8");
    sc_trace(mVcdFile, tmp_1_fu_494_p10, "tmp_1_fu_494_p10");
    sc_trace(mVcdFile, mul_ln66_fu_515_p2, "mul_ln66_fu_515_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("neural_net.hdltvin.dat");
    mHdltvoutHandle.open("neural_net.hdltvout.dat");
}

neural_net::~neural_net() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete neural_net_mux_63bkb_U1;
    delete neural_net_mux_83cud_U2;
}

void neural_net::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln53_fu_436_p2.read(), ap_const_lv1_1))) {
        i_0_reg_370 = i_reg_600.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_370 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln52_fu_424_p2.read()))) {
        j_0_reg_381 = ap_const_lv4_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        j_0_reg_381 = j_reg_608.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln53_fu_436_p2.read(), ap_const_lv1_0))) {
        k_0_reg_412 = ap_const_lv3_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        k_0_reg_412 = k_reg_621.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln53_fu_436_p2.read(), ap_const_lv1_0))) {
        sum_0_reg_392 = ap_const_lv32_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        sum_0_reg_392 = sum_fu_521_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_600 = i_fu_430_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        j_reg_608 = j_fu_442_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        k_reg_621 = k_fu_458_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln53_fu_436_p2.read(), ap_const_lv1_0))) {
        trunc_ln66_reg_613 = trunc_ln66_fu_448_p1.read();
    }
}

void neural_net::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void neural_net::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void neural_net::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void neural_net::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void neural_net::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void neural_net::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void neural_net::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln52_fu_424_p2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void neural_net::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void neural_net::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln52_fu_424_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void neural_net::thread_i_fu_430_p2() {
    i_fu_430_p2 = (!i_0_reg_370.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(i_0_reg_370.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void neural_net::thread_icmp_ln52_fu_424_p2() {
    icmp_ln52_fu_424_p2 = (!i_0_reg_370.read().is_01() || !ap_const_lv3_6.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_370.read() == ap_const_lv3_6);
}

void neural_net::thread_icmp_ln53_fu_436_p2() {
    icmp_ln53_fu_436_p2 = (!j_0_reg_381.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(j_0_reg_381.read() == ap_const_lv4_8);
}

void neural_net::thread_icmp_ln55_fu_452_p2() {
    icmp_ln55_fu_452_p2 = (!k_0_reg_412.read().is_01() || !ap_const_lv3_6.is_01())? sc_lv<1>(): sc_lv<1>(k_0_reg_412.read() == ap_const_lv3_6);
}

void neural_net::thread_in_0_address0() {
    in_0_address0 =  (sc_lv<1>) (ap_const_lv64_0);
}

void neural_net::thread_in_0_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        in_0_ce0 = ap_const_logic_1;
    } else {
        in_0_ce0 = ap_const_logic_0;
    }
}

void neural_net::thread_in_1_address0() {
    in_1_address0 =  (sc_lv<1>) (ap_const_lv64_0);
}

void neural_net::thread_in_1_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        in_1_ce0 = ap_const_logic_1;
    } else {
        in_1_ce0 = ap_const_logic_0;
    }
}

void neural_net::thread_in_2_address0() {
    in_2_address0 =  (sc_lv<1>) (ap_const_lv64_0);
}

void neural_net::thread_in_2_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        in_2_ce0 = ap_const_logic_1;
    } else {
        in_2_ce0 = ap_const_logic_0;
    }
}

void neural_net::thread_in_3_address0() {
    in_3_address0 =  (sc_lv<1>) (ap_const_lv64_0);
}

void neural_net::thread_in_3_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        in_3_ce0 = ap_const_logic_1;
    } else {
        in_3_ce0 = ap_const_logic_0;
    }
}

void neural_net::thread_in_4_address0() {
    in_4_address0 =  (sc_lv<1>) (ap_const_lv64_0);
}

void neural_net::thread_in_4_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        in_4_ce0 = ap_const_logic_1;
    } else {
        in_4_ce0 = ap_const_logic_0;
    }
}

void neural_net::thread_in_5_address0() {
    in_5_address0 =  (sc_lv<1>) (ap_const_lv64_0);
}

void neural_net::thread_in_5_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        in_5_ce0 = ap_const_logic_1;
    } else {
        in_5_ce0 = ap_const_logic_0;
    }
}

void neural_net::thread_j_fu_442_p2() {
    j_fu_442_p2 = (!j_0_reg_381.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(j_0_reg_381.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void neural_net::thread_k_fu_458_p2() {
    k_fu_458_p2 = (!k_0_reg_412.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(k_0_reg_412.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void neural_net::thread_mul_ln66_fu_515_p2() {
    mul_ln66_fu_515_p2 = (!tmp_fu_476_p8.read().is_01() || !tmp_1_fu_494_p10.read().is_01())? sc_lv<32>(): sc_bigint<32>(tmp_fu_476_p8.read()) * sc_bigint<32>(tmp_1_fu_494_p10.read());
}

void neural_net::thread_out_0_address0() {
    out_0_address0 =  (sc_lv<1>) (ap_const_lv64_0);
}

void neural_net::thread_out_0_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        out_0_ce0 = ap_const_logic_1;
    } else {
        out_0_ce0 = ap_const_logic_0;
    }
}

void neural_net::thread_out_0_d0() {
    out_0_d0 = sum_0_reg_392.read();
}

void neural_net::thread_out_0_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln55_fu_452_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,3,3>(trunc_ln66_reg_613.read(), ap_const_lv3_0))) {
        out_0_we0 = ap_const_logic_1;
    } else {
        out_0_we0 = ap_const_logic_0;
    }
}

void neural_net::thread_out_1_address0() {
    out_1_address0 =  (sc_lv<1>) (ap_const_lv64_0);
}

void neural_net::thread_out_1_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        out_1_ce0 = ap_const_logic_1;
    } else {
        out_1_ce0 = ap_const_logic_0;
    }
}

void neural_net::thread_out_1_d0() {
    out_1_d0 = sum_0_reg_392.read();
}

void neural_net::thread_out_1_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln55_fu_452_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,3,3>(trunc_ln66_reg_613.read(), ap_const_lv3_1))) {
        out_1_we0 = ap_const_logic_1;
    } else {
        out_1_we0 = ap_const_logic_0;
    }
}

void neural_net::thread_out_2_address0() {
    out_2_address0 =  (sc_lv<1>) (ap_const_lv64_0);
}

void neural_net::thread_out_2_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        out_2_ce0 = ap_const_logic_1;
    } else {
        out_2_ce0 = ap_const_logic_0;
    }
}

void neural_net::thread_out_2_d0() {
    out_2_d0 = sum_0_reg_392.read();
}

void neural_net::thread_out_2_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln55_fu_452_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,3,3>(trunc_ln66_reg_613.read(), ap_const_lv3_2))) {
        out_2_we0 = ap_const_logic_1;
    } else {
        out_2_we0 = ap_const_logic_0;
    }
}

void neural_net::thread_out_3_address0() {
    out_3_address0 =  (sc_lv<1>) (ap_const_lv64_0);
}

void neural_net::thread_out_3_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        out_3_ce0 = ap_const_logic_1;
    } else {
        out_3_ce0 = ap_const_logic_0;
    }
}

void neural_net::thread_out_3_d0() {
    out_3_d0 = sum_0_reg_392.read();
}

void neural_net::thread_out_3_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln55_fu_452_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,3,3>(trunc_ln66_reg_613.read(), ap_const_lv3_3))) {
        out_3_we0 = ap_const_logic_1;
    } else {
        out_3_we0 = ap_const_logic_0;
    }
}

void neural_net::thread_out_4_address0() {
    out_4_address0 =  (sc_lv<1>) (ap_const_lv64_0);
}

void neural_net::thread_out_4_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        out_4_ce0 = ap_const_logic_1;
    } else {
        out_4_ce0 = ap_const_logic_0;
    }
}

void neural_net::thread_out_4_d0() {
    out_4_d0 = sum_0_reg_392.read();
}

void neural_net::thread_out_4_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln55_fu_452_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,3,3>(trunc_ln66_reg_613.read(), ap_const_lv3_4))) {
        out_4_we0 = ap_const_logic_1;
    } else {
        out_4_we0 = ap_const_logic_0;
    }
}

void neural_net::thread_out_5_address0() {
    out_5_address0 =  (sc_lv<1>) (ap_const_lv64_0);
}

void neural_net::thread_out_5_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        out_5_ce0 = ap_const_logic_1;
    } else {
        out_5_ce0 = ap_const_logic_0;
    }
}

void neural_net::thread_out_5_d0() {
    out_5_d0 = sum_0_reg_392.read();
}

void neural_net::thread_out_5_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln55_fu_452_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,3,3>(trunc_ln66_reg_613.read(), ap_const_lv3_5))) {
        out_5_we0 = ap_const_logic_1;
    } else {
        out_5_we0 = ap_const_logic_0;
    }
}

void neural_net::thread_out_6_address0() {
    out_6_address0 =  (sc_lv<1>) (ap_const_lv64_0);
}

void neural_net::thread_out_6_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        out_6_ce0 = ap_const_logic_1;
    } else {
        out_6_ce0 = ap_const_logic_0;
    }
}

void neural_net::thread_out_6_d0() {
    out_6_d0 = sum_0_reg_392.read();
}

void neural_net::thread_out_6_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln55_fu_452_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,3,3>(trunc_ln66_reg_613.read(), ap_const_lv3_6))) {
        out_6_we0 = ap_const_logic_1;
    } else {
        out_6_we0 = ap_const_logic_0;
    }
}

void neural_net::thread_out_7_address0() {
    out_7_address0 =  (sc_lv<1>) (ap_const_lv64_0);
}

void neural_net::thread_out_7_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        out_7_ce0 = ap_const_logic_1;
    } else {
        out_7_ce0 = ap_const_logic_0;
    }
}

void neural_net::thread_out_7_d0() {
    out_7_d0 = sum_0_reg_392.read();
}

void neural_net::thread_out_7_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln55_fu_452_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,3,3>(trunc_ln66_reg_613.read(), ap_const_lv3_7))) {
        out_7_we0 = ap_const_logic_1;
    } else {
        out_7_we0 = ap_const_logic_0;
    }
}

void neural_net::thread_sum_fu_521_p2() {
    sum_fu_521_p2 = (!mul_ln66_fu_515_p2.read().is_01() || !sum_0_reg_392.read().is_01())? sc_lv<32>(): (sc_biguint<32>(mul_ln66_fu_515_p2.read()) + sc_biguint<32>(sum_0_reg_392.read()));
}

void neural_net::thread_trunc_ln66_fu_448_p1() {
    trunc_ln66_fu_448_p1 = j_0_reg_381.read().range(3-1, 0);
}

void neural_net::thread_weight_0_address0() {
    weight_0_address0 =  (sc_lv<3>) (zext_ln66_fu_464_p1.read());
}

void neural_net::thread_weight_0_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        weight_0_ce0 = ap_const_logic_1;
    } else {
        weight_0_ce0 = ap_const_logic_0;
    }
}

void neural_net::thread_weight_1_address0() {
    weight_1_address0 =  (sc_lv<3>) (zext_ln66_fu_464_p1.read());
}

void neural_net::thread_weight_1_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        weight_1_ce0 = ap_const_logic_1;
    } else {
        weight_1_ce0 = ap_const_logic_0;
    }
}

void neural_net::thread_weight_2_address0() {
    weight_2_address0 =  (sc_lv<3>) (zext_ln66_fu_464_p1.read());
}

void neural_net::thread_weight_2_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        weight_2_ce0 = ap_const_logic_1;
    } else {
        weight_2_ce0 = ap_const_logic_0;
    }
}

void neural_net::thread_weight_3_address0() {
    weight_3_address0 =  (sc_lv<3>) (zext_ln66_fu_464_p1.read());
}

void neural_net::thread_weight_3_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        weight_3_ce0 = ap_const_logic_1;
    } else {
        weight_3_ce0 = ap_const_logic_0;
    }
}

void neural_net::thread_weight_4_address0() {
    weight_4_address0 =  (sc_lv<3>) (zext_ln66_fu_464_p1.read());
}

void neural_net::thread_weight_4_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        weight_4_ce0 = ap_const_logic_1;
    } else {
        weight_4_ce0 = ap_const_logic_0;
    }
}

void neural_net::thread_weight_5_address0() {
    weight_5_address0 =  (sc_lv<3>) (zext_ln66_fu_464_p1.read());
}

void neural_net::thread_weight_5_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        weight_5_ce0 = ap_const_logic_1;
    } else {
        weight_5_ce0 = ap_const_logic_0;
    }
}

void neural_net::thread_weight_6_address0() {
    weight_6_address0 =  (sc_lv<3>) (zext_ln66_fu_464_p1.read());
}

void neural_net::thread_weight_6_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        weight_6_ce0 = ap_const_logic_1;
    } else {
        weight_6_ce0 = ap_const_logic_0;
    }
}

void neural_net::thread_weight_7_address0() {
    weight_7_address0 =  (sc_lv<3>) (zext_ln66_fu_464_p1.read());
}

void neural_net::thread_weight_7_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        weight_7_ce0 = ap_const_logic_1;
    } else {
        weight_7_ce0 = ap_const_logic_0;
    }
}

void neural_net::thread_zext_ln66_fu_464_p1() {
    zext_ln66_fu_464_p1 = esl_zext<64,3>(k_0_reg_412.read());
}

void neural_net::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln52_fu_424_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln53_fu_436_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln55_fu_452_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        default : 
            ap_NS_fsm = "XXXXXX";
            break;
    }
}

void neural_net::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_0_address0\" :  \"" << in_0_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_0_ce0\" :  \"" << in_0_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_0_q0\" :  \"" << in_0_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_1_address0\" :  \"" << in_1_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_1_ce0\" :  \"" << in_1_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_1_q0\" :  \"" << in_1_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_2_address0\" :  \"" << in_2_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_2_ce0\" :  \"" << in_2_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_2_q0\" :  \"" << in_2_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_3_address0\" :  \"" << in_3_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_3_ce0\" :  \"" << in_3_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_3_q0\" :  \"" << in_3_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_4_address0\" :  \"" << in_4_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_4_ce0\" :  \"" << in_4_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_4_q0\" :  \"" << in_4_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_5_address0\" :  \"" << in_5_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_5_ce0\" :  \"" << in_5_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_5_q0\" :  \"" << in_5_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_0_address0\" :  \"" << out_0_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_0_ce0\" :  \"" << out_0_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_0_we0\" :  \"" << out_0_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_0_d0\" :  \"" << out_0_d0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_1_address0\" :  \"" << out_1_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_1_ce0\" :  \"" << out_1_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_1_we0\" :  \"" << out_1_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_1_d0\" :  \"" << out_1_d0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_2_address0\" :  \"" << out_2_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_2_ce0\" :  \"" << out_2_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_2_we0\" :  \"" << out_2_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_2_d0\" :  \"" << out_2_d0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_3_address0\" :  \"" << out_3_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_3_ce0\" :  \"" << out_3_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_3_we0\" :  \"" << out_3_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_3_d0\" :  \"" << out_3_d0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_4_address0\" :  \"" << out_4_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_4_ce0\" :  \"" << out_4_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_4_we0\" :  \"" << out_4_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_4_d0\" :  \"" << out_4_d0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_5_address0\" :  \"" << out_5_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_5_ce0\" :  \"" << out_5_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_5_we0\" :  \"" << out_5_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_5_d0\" :  \"" << out_5_d0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_6_address0\" :  \"" << out_6_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_6_ce0\" :  \"" << out_6_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_6_we0\" :  \"" << out_6_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_6_d0\" :  \"" << out_6_d0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_7_address0\" :  \"" << out_7_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_7_ce0\" :  \"" << out_7_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_7_we0\" :  \"" << out_7_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_7_d0\" :  \"" << out_7_d0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"weight_0_address0\" :  \"" << weight_0_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"weight_0_ce0\" :  \"" << weight_0_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"weight_0_q0\" :  \"" << weight_0_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"weight_1_address0\" :  \"" << weight_1_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"weight_1_ce0\" :  \"" << weight_1_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"weight_1_q0\" :  \"" << weight_1_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"weight_2_address0\" :  \"" << weight_2_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"weight_2_ce0\" :  \"" << weight_2_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"weight_2_q0\" :  \"" << weight_2_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"weight_3_address0\" :  \"" << weight_3_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"weight_3_ce0\" :  \"" << weight_3_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"weight_3_q0\" :  \"" << weight_3_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"weight_4_address0\" :  \"" << weight_4_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"weight_4_ce0\" :  \"" << weight_4_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"weight_4_q0\" :  \"" << weight_4_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"weight_5_address0\" :  \"" << weight_5_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"weight_5_ce0\" :  \"" << weight_5_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"weight_5_q0\" :  \"" << weight_5_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"weight_6_address0\" :  \"" << weight_6_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"weight_6_ce0\" :  \"" << weight_6_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"weight_6_q0\" :  \"" << weight_6_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"weight_7_address0\" :  \"" << weight_7_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"weight_7_ce0\" :  \"" << weight_7_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"weight_7_q0\" :  \"" << weight_7_q0.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

