// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _neural_net_HH_
#define _neural_net_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "neural_net_mux_63bkb.h"
#include "neural_net_mux_83cud.h"

namespace ap_rtl {

struct neural_net : public sc_module {
    // Port declarations 80
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<1> > in_0_address0;
    sc_out< sc_logic > in_0_ce0;
    sc_in< sc_lv<32> > in_0_q0;
    sc_out< sc_lv<1> > in_1_address0;
    sc_out< sc_logic > in_1_ce0;
    sc_in< sc_lv<32> > in_1_q0;
    sc_out< sc_lv<1> > in_2_address0;
    sc_out< sc_logic > in_2_ce0;
    sc_in< sc_lv<32> > in_2_q0;
    sc_out< sc_lv<1> > in_3_address0;
    sc_out< sc_logic > in_3_ce0;
    sc_in< sc_lv<32> > in_3_q0;
    sc_out< sc_lv<1> > in_4_address0;
    sc_out< sc_logic > in_4_ce0;
    sc_in< sc_lv<32> > in_4_q0;
    sc_out< sc_lv<1> > in_5_address0;
    sc_out< sc_logic > in_5_ce0;
    sc_in< sc_lv<32> > in_5_q0;
    sc_out< sc_lv<1> > out_0_address0;
    sc_out< sc_logic > out_0_ce0;
    sc_out< sc_logic > out_0_we0;
    sc_out< sc_lv<32> > out_0_d0;
    sc_out< sc_lv<1> > out_1_address0;
    sc_out< sc_logic > out_1_ce0;
    sc_out< sc_logic > out_1_we0;
    sc_out< sc_lv<32> > out_1_d0;
    sc_out< sc_lv<1> > out_2_address0;
    sc_out< sc_logic > out_2_ce0;
    sc_out< sc_logic > out_2_we0;
    sc_out< sc_lv<32> > out_2_d0;
    sc_out< sc_lv<1> > out_3_address0;
    sc_out< sc_logic > out_3_ce0;
    sc_out< sc_logic > out_3_we0;
    sc_out< sc_lv<32> > out_3_d0;
    sc_out< sc_lv<1> > out_4_address0;
    sc_out< sc_logic > out_4_ce0;
    sc_out< sc_logic > out_4_we0;
    sc_out< sc_lv<32> > out_4_d0;
    sc_out< sc_lv<1> > out_5_address0;
    sc_out< sc_logic > out_5_ce0;
    sc_out< sc_logic > out_5_we0;
    sc_out< sc_lv<32> > out_5_d0;
    sc_out< sc_lv<1> > out_6_address0;
    sc_out< sc_logic > out_6_ce0;
    sc_out< sc_logic > out_6_we0;
    sc_out< sc_lv<32> > out_6_d0;
    sc_out< sc_lv<1> > out_7_address0;
    sc_out< sc_logic > out_7_ce0;
    sc_out< sc_logic > out_7_we0;
    sc_out< sc_lv<32> > out_7_d0;
    sc_out< sc_lv<3> > weight_0_address0;
    sc_out< sc_logic > weight_0_ce0;
    sc_in< sc_lv<32> > weight_0_q0;
    sc_out< sc_lv<3> > weight_1_address0;
    sc_out< sc_logic > weight_1_ce0;
    sc_in< sc_lv<32> > weight_1_q0;
    sc_out< sc_lv<3> > weight_2_address0;
    sc_out< sc_logic > weight_2_ce0;
    sc_in< sc_lv<32> > weight_2_q0;
    sc_out< sc_lv<3> > weight_3_address0;
    sc_out< sc_logic > weight_3_ce0;
    sc_in< sc_lv<32> > weight_3_q0;
    sc_out< sc_lv<3> > weight_4_address0;
    sc_out< sc_logic > weight_4_ce0;
    sc_in< sc_lv<32> > weight_4_q0;
    sc_out< sc_lv<3> > weight_5_address0;
    sc_out< sc_logic > weight_5_ce0;
    sc_in< sc_lv<32> > weight_5_q0;
    sc_out< sc_lv<3> > weight_6_address0;
    sc_out< sc_logic > weight_6_ce0;
    sc_in< sc_lv<32> > weight_6_q0;
    sc_out< sc_lv<3> > weight_7_address0;
    sc_out< sc_logic > weight_7_ce0;
    sc_in< sc_lv<32> > weight_7_q0;


    // Module declarations
    neural_net(sc_module_name name);
    SC_HAS_PROCESS(neural_net);

    ~neural_net();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    neural_net_mux_63bkb<1,1,32,32,32,32,32,32,3,32>* neural_net_mux_63bkb_U1;
    neural_net_mux_83cud<1,1,32,32,32,32,32,32,32,32,3,32>* neural_net_mux_83cud_U2;
    sc_signal< sc_lv<6> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<3> > i_fu_430_p2;
    sc_signal< sc_lv<3> > i_reg_600;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<4> > j_fu_442_p2;
    sc_signal< sc_lv<4> > j_reg_608;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<3> > trunc_ln66_fu_448_p1;
    sc_signal< sc_lv<3> > trunc_ln66_reg_613;
    sc_signal< sc_lv<1> > icmp_ln53_fu_436_p2;
    sc_signal< sc_lv<3> > k_fu_458_p2;
    sc_signal< sc_lv<3> > k_reg_621;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<1> > icmp_ln55_fu_452_p2;
    sc_signal< sc_lv<32> > sum_fu_521_p2;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<3> > i_0_reg_370;
    sc_signal< sc_lv<4> > j_0_reg_381;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<1> > icmp_ln52_fu_424_p2;
    sc_signal< sc_lv<32> > sum_0_reg_392;
    sc_signal< sc_lv<3> > k_0_reg_412;
    sc_signal< sc_lv<64> > zext_ln66_fu_464_p1;
    sc_signal< sc_lv<32> > tmp_fu_476_p8;
    sc_signal< sc_lv<32> > tmp_1_fu_494_p10;
    sc_signal< sc_lv<32> > mul_ln66_fu_515_p2;
    sc_signal< sc_lv<6> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<6> ap_ST_fsm_state1;
    static const sc_lv<6> ap_ST_fsm_state2;
    static const sc_lv<6> ap_ST_fsm_state3;
    static const sc_lv<6> ap_ST_fsm_state4;
    static const sc_lv<6> ap_ST_fsm_state5;
    static const sc_lv<6> ap_ST_fsm_state6;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_lv<3> ap_const_lv3_6;
    static const sc_lv<3> ap_const_lv3_5;
    static const sc_lv<3> ap_const_lv3_4;
    static const sc_lv<3> ap_const_lv3_3;
    static const sc_lv<3> ap_const_lv3_2;
    static const sc_lv<3> ap_const_lv3_1;
    static const sc_lv<3> ap_const_lv3_7;
    static const sc_lv<4> ap_const_lv4_8;
    static const sc_lv<4> ap_const_lv4_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_i_fu_430_p2();
    void thread_icmp_ln52_fu_424_p2();
    void thread_icmp_ln53_fu_436_p2();
    void thread_icmp_ln55_fu_452_p2();
    void thread_in_0_address0();
    void thread_in_0_ce0();
    void thread_in_1_address0();
    void thread_in_1_ce0();
    void thread_in_2_address0();
    void thread_in_2_ce0();
    void thread_in_3_address0();
    void thread_in_3_ce0();
    void thread_in_4_address0();
    void thread_in_4_ce0();
    void thread_in_5_address0();
    void thread_in_5_ce0();
    void thread_j_fu_442_p2();
    void thread_k_fu_458_p2();
    void thread_mul_ln66_fu_515_p2();
    void thread_out_0_address0();
    void thread_out_0_ce0();
    void thread_out_0_d0();
    void thread_out_0_we0();
    void thread_out_1_address0();
    void thread_out_1_ce0();
    void thread_out_1_d0();
    void thread_out_1_we0();
    void thread_out_2_address0();
    void thread_out_2_ce0();
    void thread_out_2_d0();
    void thread_out_2_we0();
    void thread_out_3_address0();
    void thread_out_3_ce0();
    void thread_out_3_d0();
    void thread_out_3_we0();
    void thread_out_4_address0();
    void thread_out_4_ce0();
    void thread_out_4_d0();
    void thread_out_4_we0();
    void thread_out_5_address0();
    void thread_out_5_ce0();
    void thread_out_5_d0();
    void thread_out_5_we0();
    void thread_out_6_address0();
    void thread_out_6_ce0();
    void thread_out_6_d0();
    void thread_out_6_we0();
    void thread_out_7_address0();
    void thread_out_7_ce0();
    void thread_out_7_d0();
    void thread_out_7_we0();
    void thread_sum_fu_521_p2();
    void thread_trunc_ln66_fu_448_p1();
    void thread_weight_0_address0();
    void thread_weight_0_ce0();
    void thread_weight_1_address0();
    void thread_weight_1_ce0();
    void thread_weight_2_address0();
    void thread_weight_2_ce0();
    void thread_weight_3_address0();
    void thread_weight_3_ce0();
    void thread_weight_4_address0();
    void thread_weight_4_ce0();
    void thread_weight_5_address0();
    void thread_weight_5_ce0();
    void thread_weight_6_address0();
    void thread_weight_6_ce0();
    void thread_weight_7_address0();
    void thread_weight_7_ce0();
    void thread_zext_ln66_fu_464_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
