// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="hw5_ex1,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-flga2104-1-i,HLS_INPUT_CLOCK=25.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.994703,HLS_SYN_LAT=5341,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=4,HLS_SYN_FF=1168,HLS_SYN_LUT=19421,HLS_VERSION=2020_1}" *)

module hw5_ex1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A,
        B_i,
        B_o,
        B_o_ap_vld
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [959:0] A;
input  [959:0] B_i;
output  [959:0] B_o;
output   B_o_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[959:0] B_o;
reg B_o_ap_vld;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [4:0] i_2_fu_235_p2;
reg   [4:0] i_2_reg_642;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln55_fu_229_p2;
wire   [4:0] i_fu_247_p2;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln11_fu_365_p2;
wire   [31:0] temp1_q0;
reg   [31:0] temp1_load_reg_674;
wire    ap_CS_fsm_state5;
wire   [63:0] zext_ln12_1_fu_382_p1;
reg   [63:0] zext_ln12_1_reg_679;
wire   [4:0] i_1_fu_387_p2;
reg   [4:0] i_1_reg_689;
wire   [4:0] i_3_fu_490_p2;
reg   [4:0] i_3_reg_702;
wire    ap_CS_fsm_state7;
wire   [0:0] icmp_ln17_fu_484_p2;
wire   [959:0] or_ln18_fu_633_p2;
wire    ap_CS_fsm_state8;
reg   [4:0] temp1_address0;
reg    temp1_ce0;
reg    temp1_we0;
wire   [31:0] temp1_d0;
wire   [4:0] temp1_address1;
reg    temp1_ce1;
wire   [31:0] temp1_q1;
reg   [4:0] temp2_address0;
reg    temp2_ce0;
reg    temp2_we0;
reg   [31:0] temp2_d0;
wire   [31:0] temp2_q0;
reg   [4:0] i_0_reg_167;
reg   [4:0] i_0_i_reg_178;
wire   [0:0] icmp_ln5_fu_241_p2;
reg   [4:0] i_0_i3_reg_189;
wire    ap_CS_fsm_state6;
reg   [959:0] out_w_0_i_reg_201;
reg   [4:0] i_0_i5_reg_212;
wire   [63:0] zext_ln55_fu_224_p1;
wire   [63:0] zext_ln6_fu_253_p1;
wire   [63:0] zext_ln12_fu_377_p1;
wire   [63:0] zext_ln12_2_fu_393_p1;
wire   [63:0] zext_ln18_fu_496_p1;
wire   [31:0] select_ln12_1_fu_475_p3;
wire   [9:0] tmp_1_fu_258_p3;
wire   [9:0] empty_8_fu_266_p2;
wire   [0:0] icmp_ln6_fu_272_p2;
wire   [9:0] sub_ln6_fu_287_p2;
wire   [9:0] sub_ln6_2_fu_299_p2;
reg   [959:0] tmp_4_fu_278_p4;
wire   [9:0] sub_ln6_1_fu_293_p2;
wire   [9:0] select_ln6_fu_305_p3;
wire   [9:0] select_ln6_2_fu_320_p3;
wire   [9:0] sub_ln6_3_fu_328_p2;
wire   [959:0] select_ln6_1_fu_313_p3;
wire   [959:0] zext_ln6_1_fu_334_p1;
wire   [959:0] zext_ln6_2_fu_338_p1;
wire   [959:0] lshr_ln6_fu_342_p2;
wire   [959:0] lshr_ln6_1_fu_348_p2;
wire   [959:0] and_ln6_fu_354_p2;
wire   [4:0] add_ln12_fu_371_p2;
wire   [31:0] add_ln12_2_fu_398_p2;
wire  signed [31:0] add_ln12_3_fu_404_p2;
wire  signed [31:0] mul_ln12_fu_413_p0;
wire   [64:0] mul_ln12_fu_413_p2;
wire   [64:0] sub_ln12_fu_419_p2;
wire   [30:0] tmp_6_fu_433_p4;
wire   [30:0] tmp_7_fu_447_p4;
wire   [0:0] tmp_5_fu_425_p3;
wire  signed [31:0] sext_ln12_1_fu_443_p1;
wire  signed [31:0] sext_ln12_2_fu_457_p1;
wire   [31:0] select_ln12_fu_461_p3;
wire   [31:0] sub_ln12_1_fu_469_p2;
wire   [9:0] shl_ln_fu_501_p3;
wire   [9:0] empty_11_fu_509_p2;
wire   [0:0] icmp_ln18_fu_515_p2;
wire   [9:0] sub_ln18_fu_525_p2;
wire   [9:0] select_ln18_fu_531_p3;
wire   [9:0] select_ln18_2_fu_547_p3;
wire   [9:0] select_ln18_1_fu_539_p3;
wire   [9:0] sub_ln18_1_fu_555_p2;
wire   [959:0] zext_ln18_1_fu_521_p1;
wire   [959:0] zext_ln18_2_fu_561_p1;
wire   [959:0] shl_ln18_fu_573_p2;
reg   [959:0] tmp_8_fu_579_p4;
wire   [959:0] zext_ln18_3_fu_565_p1;
wire   [959:0] zext_ln18_4_fu_569_p1;
wire   [959:0] shl_ln18_1_fu_597_p2;
wire   [959:0] lshr_ln18_fu_603_p2;
wire   [959:0] and_ln18_fu_609_p2;
wire   [959:0] xor_ln18_fu_615_p2;
wire   [959:0] select_ln18_3_fu_589_p3;
wire   [959:0] and_ln18_1_fu_621_p2;
wire   [959:0] and_ln18_2_fu_627_p2;
reg   [7:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
end

hw5_ex1_temp1 #(
    .DataWidth( 32 ),
    .AddressRange( 30 ),
    .AddressWidth( 5 ))
temp1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(temp1_address0),
    .ce0(temp1_ce0),
    .we0(temp1_we0),
    .d0(temp1_d0),
    .q0(temp1_q0),
    .address1(temp1_address1),
    .ce1(temp1_ce1),
    .q1(temp1_q1)
);

hw5_ex1_temp2 #(
    .DataWidth( 32 ),
    .AddressRange( 30 ),
    .AddressWidth( 5 ))
temp2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(temp2_address0),
    .ce0(temp2_ce0),
    .we0(temp2_we0),
    .d0(temp2_d0),
    .q0(temp2_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln5_fu_241_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        i_0_i3_reg_189 <= 5'd1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        i_0_i3_reg_189 <= i_1_reg_689;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        i_0_i5_reg_212 <= i_3_reg_702;
    end else if (((icmp_ln11_fu_365_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        i_0_i5_reg_212 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln5_fu_241_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        i_0_i_reg_178 <= i_fu_247_p2;
    end else if (((icmp_ln55_fu_229_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_0_i_reg_178 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln17_fu_484_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        i_0_reg_167 <= i_2_reg_642;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_0_reg_167 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        out_w_0_i_reg_201 <= or_ln18_fu_633_p2;
    end else if (((icmp_ln11_fu_365_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_w_0_i_reg_201 <= B_i;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        i_1_reg_689 <= i_1_fu_387_p2;
        temp1_load_reg_674 <= temp1_q0;
        zext_ln12_1_reg_679[4 : 0] <= zext_ln12_1_fu_382_p1[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_2_reg_642 <= i_2_fu_235_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        i_3_reg_702 <= i_3_fu_490_p2;
    end
end

always @ (*) begin
    if (((icmp_ln17_fu_484_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        B_o = out_w_0_i_reg_201;
    end else begin
        B_o = B_i;
    end
end

always @ (*) begin
    if (((icmp_ln17_fu_484_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        B_o_ap_vld = 1'b1;
    end else begin
        B_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln55_fu_229_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln55_fu_229_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        temp1_address0 = zext_ln12_1_fu_382_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        temp1_address0 = zext_ln12_fu_377_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        temp1_address0 = zext_ln6_fu_253_p1;
    end else begin
        temp1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        temp1_ce0 = 1'b1;
    end else begin
        temp1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        temp1_ce1 = 1'b1;
    end else begin
        temp1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln5_fu_241_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        temp1_we0 = 1'b1;
    end else begin
        temp1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        temp2_address0 = zext_ln18_fu_496_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        temp2_address0 = zext_ln12_1_reg_679;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        temp2_address0 = zext_ln55_fu_224_p1;
    end else begin
        temp2_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state6))) begin
        temp2_ce0 = 1'b1;
    end else begin
        temp2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        temp2_d0 = select_ln12_1_fu_475_p3;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        temp2_d0 = 32'd0;
    end else begin
        temp2_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | ((icmp_ln55_fu_229_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        temp2_we0 = 1'b1;
    end else begin
        temp2_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln55_fu_229_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln5_fu_241_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln11_fu_365_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state7 : begin
            if (((icmp_ln17_fu_484_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln12_2_fu_398_p2 = (temp1_q0 + temp1_q1);

assign add_ln12_3_fu_404_p2 = (add_ln12_2_fu_398_p2 + temp1_load_reg_674);

assign add_ln12_fu_371_p2 = ($signed(i_0_i3_reg_189) + $signed(5'd31));

assign and_ln18_1_fu_621_p2 = (xor_ln18_fu_615_p2 & out_w_0_i_reg_201);

assign and_ln18_2_fu_627_p2 = (select_ln18_3_fu_589_p3 & and_ln18_fu_609_p2);

assign and_ln18_fu_609_p2 = (shl_ln18_1_fu_597_p2 & lshr_ln18_fu_603_p2);

assign and_ln6_fu_354_p2 = (lshr_ln6_fu_342_p2 & lshr_ln6_1_fu_348_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign empty_11_fu_509_p2 = (shl_ln_fu_501_p3 | 10'd31);

assign empty_8_fu_266_p2 = (tmp_1_fu_258_p3 | 10'd31);

assign i_1_fu_387_p2 = (i_0_i3_reg_189 + 5'd1);

assign i_2_fu_235_p2 = (i_0_reg_167 + 5'd1);

assign i_3_fu_490_p2 = (i_0_i5_reg_212 + 5'd1);

assign i_fu_247_p2 = (i_0_i_reg_178 + 5'd1);

assign icmp_ln11_fu_365_p2 = ((i_0_i3_reg_189 == 5'd29) ? 1'b1 : 1'b0);

assign icmp_ln17_fu_484_p2 = ((i_0_i5_reg_212 == 5'd30) ? 1'b1 : 1'b0);

assign icmp_ln18_fu_515_p2 = ((shl_ln_fu_501_p3 > empty_11_fu_509_p2) ? 1'b1 : 1'b0);

assign icmp_ln55_fu_229_p2 = ((i_0_reg_167 == 5'd30) ? 1'b1 : 1'b0);

assign icmp_ln5_fu_241_p2 = ((i_0_i_reg_178 == 5'd30) ? 1'b1 : 1'b0);

assign icmp_ln6_fu_272_p2 = ((tmp_1_fu_258_p3 > empty_8_fu_266_p2) ? 1'b1 : 1'b0);

assign lshr_ln18_fu_603_p2 = 960'd9745314011399999080353382387875188310876226857595007526867906457212948690766426102465615065882010259225304916231408668183459169865203094046577987296312653419531277699956473029870789655490053648352799593479218378873685597925394874945746363615468965612827738803104277547081828589991914110975 >> zext_ln18_4_fu_569_p1;

assign lshr_ln6_1_fu_348_p2 = 960'd9745314011399999080353382387875188310876226857595007526867906457212948690766426102465615065882010259225304916231408668183459169865203094046577987296312653419531277699956473029870789655490053648352799593479218378873685597925394874945746363615468965612827738803104277547081828589991914110975 >> zext_ln6_2_fu_338_p1;

assign lshr_ln6_fu_342_p2 = select_ln6_1_fu_313_p3 >> zext_ln6_1_fu_334_p1;

assign mul_ln12_fu_413_p0 = add_ln12_3_fu_404_p2;

assign mul_ln12_fu_413_p2 = ($signed(mul_ln12_fu_413_p0) * $signed(65'h155555556));

assign or_ln18_fu_633_p2 = (and_ln18_2_fu_627_p2 | and_ln18_1_fu_621_p2);

assign select_ln12_1_fu_475_p3 = ((tmp_5_fu_425_p3[0:0] === 1'b1) ? sub_ln12_1_fu_469_p2 : sext_ln12_2_fu_457_p1);

assign select_ln12_fu_461_p3 = ((tmp_5_fu_425_p3[0:0] === 1'b1) ? sext_ln12_1_fu_443_p1 : sext_ln12_2_fu_457_p1);

assign select_ln18_1_fu_539_p3 = ((icmp_ln18_fu_515_p2[0:0] === 1'b1) ? empty_11_fu_509_p2 : shl_ln_fu_501_p3);

assign select_ln18_2_fu_547_p3 = ((icmp_ln18_fu_515_p2[0:0] === 1'b1) ? sub_ln18_fu_525_p2 : shl_ln_fu_501_p3);

assign select_ln18_3_fu_589_p3 = ((icmp_ln18_fu_515_p2[0:0] === 1'b1) ? tmp_8_fu_579_p4 : shl_ln18_fu_573_p2);

assign select_ln18_fu_531_p3 = ((icmp_ln18_fu_515_p2[0:0] === 1'b1) ? shl_ln_fu_501_p3 : empty_11_fu_509_p2);

assign select_ln6_1_fu_313_p3 = ((icmp_ln6_fu_272_p2[0:0] === 1'b1) ? tmp_4_fu_278_p4 : A);

assign select_ln6_2_fu_320_p3 = ((icmp_ln6_fu_272_p2[0:0] === 1'b1) ? sub_ln6_1_fu_293_p2 : tmp_1_fu_258_p3);

assign select_ln6_fu_305_p3 = ((icmp_ln6_fu_272_p2[0:0] === 1'b1) ? sub_ln6_fu_287_p2 : sub_ln6_2_fu_299_p2);

assign sext_ln12_1_fu_443_p1 = $signed(tmp_6_fu_433_p4);

assign sext_ln12_2_fu_457_p1 = $signed(tmp_7_fu_447_p4);

assign shl_ln18_1_fu_597_p2 = 960'd9745314011399999080353382387875188310876226857595007526867906457212948690766426102465615065882010259225304916231408668183459169865203094046577987296312653419531277699956473029870789655490053648352799593479218378873685597925394874945746363615468965612827738803104277547081828589991914110975 << zext_ln18_3_fu_565_p1;

assign shl_ln18_fu_573_p2 = zext_ln18_1_fu_521_p1 << zext_ln18_2_fu_561_p1;

assign shl_ln_fu_501_p3 = {{i_0_i5_reg_212}, {5'd0}};

assign sub_ln12_1_fu_469_p2 = (32'd0 - select_ln12_fu_461_p3);

assign sub_ln12_fu_419_p2 = (65'd0 - mul_ln12_fu_413_p2);

assign sub_ln18_1_fu_555_p2 = ($signed(10'd959) - $signed(select_ln18_fu_531_p3));

assign sub_ln18_fu_525_p2 = ($signed(10'd959) - $signed(shl_ln_fu_501_p3));

assign sub_ln6_1_fu_293_p2 = ($signed(10'd959) - $signed(tmp_1_fu_258_p3));

assign sub_ln6_2_fu_299_p2 = (empty_8_fu_266_p2 - tmp_1_fu_258_p3);

assign sub_ln6_3_fu_328_p2 = ($signed(10'd959) - $signed(select_ln6_fu_305_p3));

assign sub_ln6_fu_287_p2 = (tmp_1_fu_258_p3 - empty_8_fu_266_p2);

assign temp1_address1 = zext_ln12_2_fu_393_p1;

assign temp1_d0 = and_ln6_fu_354_p2[31:0];

assign tmp_1_fu_258_p3 = {{i_0_i_reg_178}, {5'd0}};

integer ap_tvar_int_0;

always @ (A) begin
    for (ap_tvar_int_0 = 960 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 959 - 0) begin
            tmp_4_fu_278_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            tmp_4_fu_278_p4[ap_tvar_int_0] = A[959 - ap_tvar_int_0];
        end
    end
end

assign tmp_5_fu_425_p3 = add_ln12_3_fu_404_p2[32'd31];

assign tmp_6_fu_433_p4 = {{sub_ln12_fu_419_p2[64:34]}};

assign tmp_7_fu_447_p4 = {{mul_ln12_fu_413_p2[64:34]}};

integer ap_tvar_int_1;

always @ (shl_ln18_fu_573_p2) begin
    for (ap_tvar_int_1 = 960 - 1; ap_tvar_int_1 >= 0; ap_tvar_int_1 = ap_tvar_int_1 - 1) begin
        if (ap_tvar_int_1 > 959 - 0) begin
            tmp_8_fu_579_p4[ap_tvar_int_1] = 1'b0;
        end else begin
            tmp_8_fu_579_p4[ap_tvar_int_1] = shl_ln18_fu_573_p2[959 - ap_tvar_int_1];
        end
    end
end

assign xor_ln18_fu_615_p2 = (960'd9745314011399999080353382387875188310876226857595007526867906457212948690766426102465615065882010259225304916231408668183459169865203094046577987296312653419531277699956473029870789655490053648352799593479218378873685597925394874945746363615468965612827738803104277547081828589991914110975 ^ and_ln18_fu_609_p2);

assign zext_ln12_1_fu_382_p1 = i_0_i3_reg_189;

assign zext_ln12_2_fu_393_p1 = i_1_fu_387_p2;

assign zext_ln12_fu_377_p1 = add_ln12_fu_371_p2;

assign zext_ln18_1_fu_521_p1 = temp2_q0;

assign zext_ln18_2_fu_561_p1 = select_ln18_2_fu_547_p3;

assign zext_ln18_3_fu_565_p1 = select_ln18_1_fu_539_p3;

assign zext_ln18_4_fu_569_p1 = sub_ln18_1_fu_555_p2;

assign zext_ln18_fu_496_p1 = i_0_i5_reg_212;

assign zext_ln55_fu_224_p1 = i_0_reg_167;

assign zext_ln6_1_fu_334_p1 = select_ln6_2_fu_320_p3;

assign zext_ln6_2_fu_338_p1 = sub_ln6_3_fu_328_p2;

assign zext_ln6_fu_253_p1 = i_0_i_reg_178;

always @ (posedge ap_clk) begin
    zext_ln12_1_reg_679[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
end

endmodule //hw5_ex1
