-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity neural_net is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_0_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    in_0_ce0 : OUT STD_LOGIC;
    in_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    in_1_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    in_1_ce0 : OUT STD_LOGIC;
    in_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    in_2_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    in_2_ce0 : OUT STD_LOGIC;
    in_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    in_3_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    in_3_ce0 : OUT STD_LOGIC;
    in_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    in_4_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    in_4_ce0 : OUT STD_LOGIC;
    in_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    in_5_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    in_5_ce0 : OUT STD_LOGIC;
    in_5_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    out_0_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_0_ce0 : OUT STD_LOGIC;
    out_0_we0 : OUT STD_LOGIC;
    out_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_1_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_1_ce0 : OUT STD_LOGIC;
    out_1_we0 : OUT STD_LOGIC;
    out_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_2_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_2_ce0 : OUT STD_LOGIC;
    out_2_we0 : OUT STD_LOGIC;
    out_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_3_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_3_ce0 : OUT STD_LOGIC;
    out_3_we0 : OUT STD_LOGIC;
    out_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_4_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_4_ce0 : OUT STD_LOGIC;
    out_4_we0 : OUT STD_LOGIC;
    out_4_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_5_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_5_ce0 : OUT STD_LOGIC;
    out_5_we0 : OUT STD_LOGIC;
    out_5_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_6_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_6_ce0 : OUT STD_LOGIC;
    out_6_we0 : OUT STD_LOGIC;
    out_6_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_7_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_7_ce0 : OUT STD_LOGIC;
    out_7_we0 : OUT STD_LOGIC;
    out_7_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    weight_0_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    weight_0_ce0 : OUT STD_LOGIC;
    weight_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weight_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    weight_1_ce0 : OUT STD_LOGIC;
    weight_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weight_2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    weight_2_ce0 : OUT STD_LOGIC;
    weight_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weight_3_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    weight_3_ce0 : OUT STD_LOGIC;
    weight_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weight_4_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    weight_4_ce0 : OUT STD_LOGIC;
    weight_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weight_5_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    weight_5_ce0 : OUT STD_LOGIC;
    weight_5_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weight_6_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    weight_6_ce0 : OUT STD_LOGIC;
    weight_6_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weight_7_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    weight_7_ce0 : OUT STD_LOGIC;
    weight_7_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of neural_net is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "neural_net,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-flga2104-1-i,HLS_INPUT_CLOCK=25.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.527000,HLS_SYN_LAT=733,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=3,HLS_SYN_FF=61,HLS_SYN_LUT=262,HLS_VERSION=2020_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal i_fu_430_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal i_reg_600 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal j_fu_442_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal j_reg_608 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal trunc_ln66_fu_448_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln66_reg_613 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln53_fu_436_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal k_fu_458_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal k_reg_621 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln55_fu_452_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sum_fu_521_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal i_0_reg_370 : STD_LOGIC_VECTOR (2 downto 0);
    signal j_0_reg_381 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal icmp_ln52_fu_424_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sum_0_reg_392 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_0_reg_412 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln66_fu_464_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_fu_476_p8 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_494_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln66_fu_515_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);

    component neural_net_mux_63bkb IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component neural_net_mux_83cud IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (31 downto 0);
        din7 : IN STD_LOGIC_VECTOR (31 downto 0);
        din8 : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    neural_net_mux_63bkb_U1 : component neural_net_mux_63bkb
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 32,
        din5_WIDTH => 32,
        din6_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => in_0_q0,
        din1 => in_1_q0,
        din2 => in_2_q0,
        din3 => in_3_q0,
        din4 => in_4_q0,
        din5 => in_5_q0,
        din6 => k_0_reg_412,
        dout => tmp_fu_476_p8);

    neural_net_mux_83cud_U2 : component neural_net_mux_83cud
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 32,
        din5_WIDTH => 32,
        din6_WIDTH => 32,
        din7_WIDTH => 32,
        din8_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => weight_0_q0,
        din1 => weight_1_q0,
        din2 => weight_2_q0,
        din3 => weight_3_q0,
        din4 => weight_4_q0,
        din5 => weight_5_q0,
        din6 => weight_6_q0,
        din7 => weight_7_q0,
        din8 => trunc_ln66_reg_613,
        dout => tmp_1_fu_494_p10);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    i_0_reg_370_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln53_fu_436_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                i_0_reg_370 <= i_reg_600;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_0_reg_370 <= ap_const_lv3_0;
            end if; 
        end if;
    end process;

    j_0_reg_381_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln52_fu_424_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                j_0_reg_381 <= ap_const_lv4_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                j_0_reg_381 <= j_reg_608;
            end if; 
        end if;
    end process;

    k_0_reg_412_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln53_fu_436_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                k_0_reg_412 <= ap_const_lv3_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                k_0_reg_412 <= k_reg_621;
            end if; 
        end if;
    end process;

    sum_0_reg_392_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln53_fu_436_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                sum_0_reg_392 <= ap_const_lv32_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                sum_0_reg_392 <= sum_fu_521_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                i_reg_600 <= i_fu_430_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                j_reg_608 <= j_fu_442_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                k_reg_621 <= k_fu_458_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln53_fu_436_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                trunc_ln66_reg_613 <= trunc_ln66_fu_448_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, icmp_ln53_fu_436_p2, ap_CS_fsm_state4, icmp_ln55_fu_452_p2, icmp_ln52_fu_424_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln52_fu_424_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln53_fu_436_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((icmp_ln55_fu_452_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_done_assign_proc : process(ap_CS_fsm_state2, icmp_ln52_fu_424_p2)
    begin
        if (((icmp_ln52_fu_424_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln52_fu_424_p2)
    begin
        if (((icmp_ln52_fu_424_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    i_fu_430_p2 <= std_logic_vector(unsigned(i_0_reg_370) + unsigned(ap_const_lv3_1));
    icmp_ln52_fu_424_p2 <= "1" when (i_0_reg_370 = ap_const_lv3_6) else "0";
    icmp_ln53_fu_436_p2 <= "1" when (j_0_reg_381 = ap_const_lv4_8) else "0";
    icmp_ln55_fu_452_p2 <= "1" when (k_0_reg_412 = ap_const_lv3_6) else "0";
    in_0_address0 <= ap_const_lv64_0(1 - 1 downto 0);

    in_0_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            in_0_ce0 <= ap_const_logic_1;
        else 
            in_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    in_1_address0 <= ap_const_lv64_0(1 - 1 downto 0);

    in_1_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            in_1_ce0 <= ap_const_logic_1;
        else 
            in_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    in_2_address0 <= ap_const_lv64_0(1 - 1 downto 0);

    in_2_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            in_2_ce0 <= ap_const_logic_1;
        else 
            in_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    in_3_address0 <= ap_const_lv64_0(1 - 1 downto 0);

    in_3_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            in_3_ce0 <= ap_const_logic_1;
        else 
            in_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    in_4_address0 <= ap_const_lv64_0(1 - 1 downto 0);

    in_4_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            in_4_ce0 <= ap_const_logic_1;
        else 
            in_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    in_5_address0 <= ap_const_lv64_0(1 - 1 downto 0);

    in_5_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            in_5_ce0 <= ap_const_logic_1;
        else 
            in_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    j_fu_442_p2 <= std_logic_vector(unsigned(j_0_reg_381) + unsigned(ap_const_lv4_1));
    k_fu_458_p2 <= std_logic_vector(unsigned(k_0_reg_412) + unsigned(ap_const_lv3_1));
    mul_ln66_fu_515_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(tmp_fu_476_p8) * signed(tmp_1_fu_494_p10))), 32));
    out_0_address0 <= ap_const_lv64_0(1 - 1 downto 0);

    out_0_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            out_0_ce0 <= ap_const_logic_1;
        else 
            out_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    out_0_d0 <= sum_0_reg_392;

    out_0_we0_assign_proc : process(trunc_ln66_reg_613, ap_CS_fsm_state4, icmp_ln55_fu_452_p2)
    begin
        if (((icmp_ln55_fu_452_p2 = ap_const_lv1_1) and (trunc_ln66_reg_613 = ap_const_lv3_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            out_0_we0 <= ap_const_logic_1;
        else 
            out_0_we0 <= ap_const_logic_0;
        end if; 
    end process;

    out_1_address0 <= ap_const_lv64_0(1 - 1 downto 0);

    out_1_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            out_1_ce0 <= ap_const_logic_1;
        else 
            out_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    out_1_d0 <= sum_0_reg_392;

    out_1_we0_assign_proc : process(trunc_ln66_reg_613, ap_CS_fsm_state4, icmp_ln55_fu_452_p2)
    begin
        if (((icmp_ln55_fu_452_p2 = ap_const_lv1_1) and (trunc_ln66_reg_613 = ap_const_lv3_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            out_1_we0 <= ap_const_logic_1;
        else 
            out_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    out_2_address0 <= ap_const_lv64_0(1 - 1 downto 0);

    out_2_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            out_2_ce0 <= ap_const_logic_1;
        else 
            out_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    out_2_d0 <= sum_0_reg_392;

    out_2_we0_assign_proc : process(trunc_ln66_reg_613, ap_CS_fsm_state4, icmp_ln55_fu_452_p2)
    begin
        if (((icmp_ln55_fu_452_p2 = ap_const_lv1_1) and (trunc_ln66_reg_613 = ap_const_lv3_2) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            out_2_we0 <= ap_const_logic_1;
        else 
            out_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    out_3_address0 <= ap_const_lv64_0(1 - 1 downto 0);

    out_3_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            out_3_ce0 <= ap_const_logic_1;
        else 
            out_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    out_3_d0 <= sum_0_reg_392;

    out_3_we0_assign_proc : process(trunc_ln66_reg_613, ap_CS_fsm_state4, icmp_ln55_fu_452_p2)
    begin
        if (((icmp_ln55_fu_452_p2 = ap_const_lv1_1) and (trunc_ln66_reg_613 = ap_const_lv3_3) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            out_3_we0 <= ap_const_logic_1;
        else 
            out_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    out_4_address0 <= ap_const_lv64_0(1 - 1 downto 0);

    out_4_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            out_4_ce0 <= ap_const_logic_1;
        else 
            out_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    out_4_d0 <= sum_0_reg_392;

    out_4_we0_assign_proc : process(trunc_ln66_reg_613, ap_CS_fsm_state4, icmp_ln55_fu_452_p2)
    begin
        if (((icmp_ln55_fu_452_p2 = ap_const_lv1_1) and (trunc_ln66_reg_613 = ap_const_lv3_4) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            out_4_we0 <= ap_const_logic_1;
        else 
            out_4_we0 <= ap_const_logic_0;
        end if; 
    end process;

    out_5_address0 <= ap_const_lv64_0(1 - 1 downto 0);

    out_5_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            out_5_ce0 <= ap_const_logic_1;
        else 
            out_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    out_5_d0 <= sum_0_reg_392;

    out_5_we0_assign_proc : process(trunc_ln66_reg_613, ap_CS_fsm_state4, icmp_ln55_fu_452_p2)
    begin
        if (((icmp_ln55_fu_452_p2 = ap_const_lv1_1) and (trunc_ln66_reg_613 = ap_const_lv3_5) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            out_5_we0 <= ap_const_logic_1;
        else 
            out_5_we0 <= ap_const_logic_0;
        end if; 
    end process;

    out_6_address0 <= ap_const_lv64_0(1 - 1 downto 0);

    out_6_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            out_6_ce0 <= ap_const_logic_1;
        else 
            out_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    out_6_d0 <= sum_0_reg_392;

    out_6_we0_assign_proc : process(trunc_ln66_reg_613, ap_CS_fsm_state4, icmp_ln55_fu_452_p2)
    begin
        if (((icmp_ln55_fu_452_p2 = ap_const_lv1_1) and (trunc_ln66_reg_613 = ap_const_lv3_6) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            out_6_we0 <= ap_const_logic_1;
        else 
            out_6_we0 <= ap_const_logic_0;
        end if; 
    end process;

    out_7_address0 <= ap_const_lv64_0(1 - 1 downto 0);

    out_7_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            out_7_ce0 <= ap_const_logic_1;
        else 
            out_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    out_7_d0 <= sum_0_reg_392;

    out_7_we0_assign_proc : process(trunc_ln66_reg_613, ap_CS_fsm_state4, icmp_ln55_fu_452_p2)
    begin
        if (((icmp_ln55_fu_452_p2 = ap_const_lv1_1) and (trunc_ln66_reg_613 = ap_const_lv3_7) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            out_7_we0 <= ap_const_logic_1;
        else 
            out_7_we0 <= ap_const_logic_0;
        end if; 
    end process;

    sum_fu_521_p2 <= std_logic_vector(unsigned(mul_ln66_fu_515_p2) + unsigned(sum_0_reg_392));
    trunc_ln66_fu_448_p1 <= j_0_reg_381(3 - 1 downto 0);
    weight_0_address0 <= zext_ln66_fu_464_p1(3 - 1 downto 0);

    weight_0_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weight_0_ce0 <= ap_const_logic_1;
        else 
            weight_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    weight_1_address0 <= zext_ln66_fu_464_p1(3 - 1 downto 0);

    weight_1_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weight_1_ce0 <= ap_const_logic_1;
        else 
            weight_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    weight_2_address0 <= zext_ln66_fu_464_p1(3 - 1 downto 0);

    weight_2_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weight_2_ce0 <= ap_const_logic_1;
        else 
            weight_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    weight_3_address0 <= zext_ln66_fu_464_p1(3 - 1 downto 0);

    weight_3_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weight_3_ce0 <= ap_const_logic_1;
        else 
            weight_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    weight_4_address0 <= zext_ln66_fu_464_p1(3 - 1 downto 0);

    weight_4_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weight_4_ce0 <= ap_const_logic_1;
        else 
            weight_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    weight_5_address0 <= zext_ln66_fu_464_p1(3 - 1 downto 0);

    weight_5_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weight_5_ce0 <= ap_const_logic_1;
        else 
            weight_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    weight_6_address0 <= zext_ln66_fu_464_p1(3 - 1 downto 0);

    weight_6_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weight_6_ce0 <= ap_const_logic_1;
        else 
            weight_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    weight_7_address0 <= zext_ln66_fu_464_p1(3 - 1 downto 0);

    weight_7_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weight_7_ce0 <= ap_const_logic_1;
        else 
            weight_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln66_fu_464_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(k_0_reg_412),64));
end behav;
