// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="neural_net,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-flga2104-1-i,HLS_INPUT_CLOCK=25.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.527000,HLS_SYN_LAT=733,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=3,HLS_SYN_FF=61,HLS_SYN_LUT=262,HLS_VERSION=2020_1}" *)

module neural_net (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_0_address0,
        in_0_ce0,
        in_0_q0,
        in_1_address0,
        in_1_ce0,
        in_1_q0,
        in_2_address0,
        in_2_ce0,
        in_2_q0,
        in_3_address0,
        in_3_ce0,
        in_3_q0,
        in_4_address0,
        in_4_ce0,
        in_4_q0,
        in_5_address0,
        in_5_ce0,
        in_5_q0,
        out_0_address0,
        out_0_ce0,
        out_0_we0,
        out_0_d0,
        out_1_address0,
        out_1_ce0,
        out_1_we0,
        out_1_d0,
        out_2_address0,
        out_2_ce0,
        out_2_we0,
        out_2_d0,
        out_3_address0,
        out_3_ce0,
        out_3_we0,
        out_3_d0,
        out_4_address0,
        out_4_ce0,
        out_4_we0,
        out_4_d0,
        out_5_address0,
        out_5_ce0,
        out_5_we0,
        out_5_d0,
        out_6_address0,
        out_6_ce0,
        out_6_we0,
        out_6_d0,
        out_7_address0,
        out_7_ce0,
        out_7_we0,
        out_7_d0,
        weight_0_address0,
        weight_0_ce0,
        weight_0_q0,
        weight_1_address0,
        weight_1_ce0,
        weight_1_q0,
        weight_2_address0,
        weight_2_ce0,
        weight_2_q0,
        weight_3_address0,
        weight_3_ce0,
        weight_3_q0,
        weight_4_address0,
        weight_4_ce0,
        weight_4_q0,
        weight_5_address0,
        weight_5_ce0,
        weight_5_q0,
        weight_6_address0,
        weight_6_ce0,
        weight_6_q0,
        weight_7_address0,
        weight_7_ce0,
        weight_7_q0
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [0:0] in_0_address0;
output   in_0_ce0;
input  [31:0] in_0_q0;
output  [0:0] in_1_address0;
output   in_1_ce0;
input  [31:0] in_1_q0;
output  [0:0] in_2_address0;
output   in_2_ce0;
input  [31:0] in_2_q0;
output  [0:0] in_3_address0;
output   in_3_ce0;
input  [31:0] in_3_q0;
output  [0:0] in_4_address0;
output   in_4_ce0;
input  [31:0] in_4_q0;
output  [0:0] in_5_address0;
output   in_5_ce0;
input  [31:0] in_5_q0;
output  [0:0] out_0_address0;
output   out_0_ce0;
output   out_0_we0;
output  [31:0] out_0_d0;
output  [0:0] out_1_address0;
output   out_1_ce0;
output   out_1_we0;
output  [31:0] out_1_d0;
output  [0:0] out_2_address0;
output   out_2_ce0;
output   out_2_we0;
output  [31:0] out_2_d0;
output  [0:0] out_3_address0;
output   out_3_ce0;
output   out_3_we0;
output  [31:0] out_3_d0;
output  [0:0] out_4_address0;
output   out_4_ce0;
output   out_4_we0;
output  [31:0] out_4_d0;
output  [0:0] out_5_address0;
output   out_5_ce0;
output   out_5_we0;
output  [31:0] out_5_d0;
output  [0:0] out_6_address0;
output   out_6_ce0;
output   out_6_we0;
output  [31:0] out_6_d0;
output  [0:0] out_7_address0;
output   out_7_ce0;
output   out_7_we0;
output  [31:0] out_7_d0;
output  [2:0] weight_0_address0;
output   weight_0_ce0;
input  [31:0] weight_0_q0;
output  [2:0] weight_1_address0;
output   weight_1_ce0;
input  [31:0] weight_1_q0;
output  [2:0] weight_2_address0;
output   weight_2_ce0;
input  [31:0] weight_2_q0;
output  [2:0] weight_3_address0;
output   weight_3_ce0;
input  [31:0] weight_3_q0;
output  [2:0] weight_4_address0;
output   weight_4_ce0;
input  [31:0] weight_4_q0;
output  [2:0] weight_5_address0;
output   weight_5_ce0;
input  [31:0] weight_5_q0;
output  [2:0] weight_6_address0;
output   weight_6_ce0;
input  [31:0] weight_6_q0;
output  [2:0] weight_7_address0;
output   weight_7_ce0;
input  [31:0] weight_7_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_0_ce0;
reg in_1_ce0;
reg in_2_ce0;
reg in_3_ce0;
reg in_4_ce0;
reg in_5_ce0;
reg out_0_ce0;
reg out_0_we0;
reg out_1_ce0;
reg out_1_we0;
reg out_2_ce0;
reg out_2_we0;
reg out_3_ce0;
reg out_3_we0;
reg out_4_ce0;
reg out_4_we0;
reg out_5_ce0;
reg out_5_we0;
reg out_6_ce0;
reg out_6_we0;
reg out_7_ce0;
reg out_7_we0;
reg weight_0_ce0;
reg weight_1_ce0;
reg weight_2_ce0;
reg weight_3_ce0;
reg weight_4_ce0;
reg weight_5_ce0;
reg weight_6_ce0;
reg weight_7_ce0;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [2:0] i_fu_430_p2;
reg   [2:0] i_reg_600;
wire    ap_CS_fsm_state2;
wire   [3:0] j_fu_442_p2;
reg   [3:0] j_reg_608;
wire    ap_CS_fsm_state3;
wire   [2:0] trunc_ln66_fu_448_p1;
reg   [2:0] trunc_ln66_reg_613;
wire   [0:0] icmp_ln53_fu_436_p2;
wire   [2:0] k_fu_458_p2;
reg   [2:0] k_reg_621;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln55_fu_452_p2;
wire   [31:0] sum_fu_521_p2;
wire    ap_CS_fsm_state5;
reg   [2:0] i_0_reg_370;
reg   [3:0] j_0_reg_381;
wire    ap_CS_fsm_state6;
wire   [0:0] icmp_ln52_fu_424_p2;
reg   [31:0] sum_0_reg_392;
reg   [2:0] k_0_reg_412;
wire   [63:0] zext_ln66_fu_464_p1;
wire  signed [31:0] tmp_fu_476_p8;
wire  signed [31:0] tmp_1_fu_494_p10;
wire   [31:0] mul_ln66_fu_515_p2;
reg   [5:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
end

neural_net_mux_63bkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
neural_net_mux_63bkb_U1(
    .din0(in_0_q0),
    .din1(in_1_q0),
    .din2(in_2_q0),
    .din3(in_3_q0),
    .din4(in_4_q0),
    .din5(in_5_q0),
    .din6(k_0_reg_412),
    .dout(tmp_fu_476_p8)
);

neural_net_mux_83cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
neural_net_mux_83cud_U2(
    .din0(weight_0_q0),
    .din1(weight_1_q0),
    .din2(weight_2_q0),
    .din3(weight_3_q0),
    .din4(weight_4_q0),
    .din5(weight_5_q0),
    .din6(weight_6_q0),
    .din7(weight_7_q0),
    .din8(trunc_ln66_reg_613),
    .dout(tmp_1_fu_494_p10)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln53_fu_436_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        i_0_reg_370 <= i_reg_600;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_0_reg_370 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln52_fu_424_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        j_0_reg_381 <= 4'd0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        j_0_reg_381 <= j_reg_608;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln53_fu_436_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        k_0_reg_412 <= 3'd0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        k_0_reg_412 <= k_reg_621;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln53_fu_436_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        sum_0_reg_392 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        sum_0_reg_392 <= sum_fu_521_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_reg_600 <= i_fu_430_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        j_reg_608 <= j_fu_442_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        k_reg_621 <= k_fu_458_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln53_fu_436_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        trunc_ln66_reg_613 <= trunc_ln66_fu_448_p1;
    end
end

always @ (*) begin
    if (((icmp_ln52_fu_424_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln52_fu_424_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        in_0_ce0 = 1'b1;
    end else begin
        in_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        in_1_ce0 = 1'b1;
    end else begin
        in_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        in_2_ce0 = 1'b1;
    end else begin
        in_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        in_3_ce0 = 1'b1;
    end else begin
        in_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        in_4_ce0 = 1'b1;
    end else begin
        in_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        in_5_ce0 = 1'b1;
    end else begin
        in_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        out_0_ce0 = 1'b1;
    end else begin
        out_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln55_fu_452_p2 == 1'd1) & (trunc_ln66_reg_613 == 3'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        out_0_we0 = 1'b1;
    end else begin
        out_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        out_1_ce0 = 1'b1;
    end else begin
        out_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln55_fu_452_p2 == 1'd1) & (trunc_ln66_reg_613 == 3'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_1_we0 = 1'b1;
    end else begin
        out_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        out_2_ce0 = 1'b1;
    end else begin
        out_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln55_fu_452_p2 == 1'd1) & (trunc_ln66_reg_613 == 3'd2) & (1'b1 == ap_CS_fsm_state4))) begin
        out_2_we0 = 1'b1;
    end else begin
        out_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        out_3_ce0 = 1'b1;
    end else begin
        out_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln55_fu_452_p2 == 1'd1) & (trunc_ln66_reg_613 == 3'd3) & (1'b1 == ap_CS_fsm_state4))) begin
        out_3_we0 = 1'b1;
    end else begin
        out_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        out_4_ce0 = 1'b1;
    end else begin
        out_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln55_fu_452_p2 == 1'd1) & (trunc_ln66_reg_613 == 3'd4) & (1'b1 == ap_CS_fsm_state4))) begin
        out_4_we0 = 1'b1;
    end else begin
        out_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        out_5_ce0 = 1'b1;
    end else begin
        out_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln55_fu_452_p2 == 1'd1) & (trunc_ln66_reg_613 == 3'd5) & (1'b1 == ap_CS_fsm_state4))) begin
        out_5_we0 = 1'b1;
    end else begin
        out_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        out_6_ce0 = 1'b1;
    end else begin
        out_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln55_fu_452_p2 == 1'd1) & (trunc_ln66_reg_613 == 3'd6) & (1'b1 == ap_CS_fsm_state4))) begin
        out_6_we0 = 1'b1;
    end else begin
        out_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        out_7_ce0 = 1'b1;
    end else begin
        out_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln55_fu_452_p2 == 1'd1) & (trunc_ln66_reg_613 == 3'd7) & (1'b1 == ap_CS_fsm_state4))) begin
        out_7_we0 = 1'b1;
    end else begin
        out_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        weight_0_ce0 = 1'b1;
    end else begin
        weight_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        weight_1_ce0 = 1'b1;
    end else begin
        weight_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        weight_2_ce0 = 1'b1;
    end else begin
        weight_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        weight_3_ce0 = 1'b1;
    end else begin
        weight_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        weight_4_ce0 = 1'b1;
    end else begin
        weight_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        weight_5_ce0 = 1'b1;
    end else begin
        weight_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        weight_6_ce0 = 1'b1;
    end else begin
        weight_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        weight_7_ce0 = 1'b1;
    end else begin
        weight_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln52_fu_424_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln53_fu_436_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln55_fu_452_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign i_fu_430_p2 = (i_0_reg_370 + 3'd1);

assign icmp_ln52_fu_424_p2 = ((i_0_reg_370 == 3'd6) ? 1'b1 : 1'b0);

assign icmp_ln53_fu_436_p2 = ((j_0_reg_381 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln55_fu_452_p2 = ((k_0_reg_412 == 3'd6) ? 1'b1 : 1'b0);

assign in_0_address0 = 64'd0;

assign in_1_address0 = 64'd0;

assign in_2_address0 = 64'd0;

assign in_3_address0 = 64'd0;

assign in_4_address0 = 64'd0;

assign in_5_address0 = 64'd0;

assign j_fu_442_p2 = (j_0_reg_381 + 4'd1);

assign k_fu_458_p2 = (k_0_reg_412 + 3'd1);

assign mul_ln66_fu_515_p2 = ($signed(tmp_fu_476_p8) * $signed(tmp_1_fu_494_p10));

assign out_0_address0 = 64'd0;

assign out_0_d0 = sum_0_reg_392;

assign out_1_address0 = 64'd0;

assign out_1_d0 = sum_0_reg_392;

assign out_2_address0 = 64'd0;

assign out_2_d0 = sum_0_reg_392;

assign out_3_address0 = 64'd0;

assign out_3_d0 = sum_0_reg_392;

assign out_4_address0 = 64'd0;

assign out_4_d0 = sum_0_reg_392;

assign out_5_address0 = 64'd0;

assign out_5_d0 = sum_0_reg_392;

assign out_6_address0 = 64'd0;

assign out_6_d0 = sum_0_reg_392;

assign out_7_address0 = 64'd0;

assign out_7_d0 = sum_0_reg_392;

assign sum_fu_521_p2 = (mul_ln66_fu_515_p2 + sum_0_reg_392);

assign trunc_ln66_fu_448_p1 = j_0_reg_381[2:0];

assign weight_0_address0 = zext_ln66_fu_464_p1;

assign weight_1_address0 = zext_ln66_fu_464_p1;

assign weight_2_address0 = zext_ln66_fu_464_p1;

assign weight_3_address0 = zext_ln66_fu_464_p1;

assign weight_4_address0 = zext_ln66_fu_464_p1;

assign weight_5_address0 = zext_ln66_fu_464_p1;

assign weight_6_address0 = zext_ln66_fu_464_p1;

assign weight_7_address0 = zext_ln66_fu_464_p1;

assign zext_ln66_fu_464_p1 = k_0_reg_412;

endmodule //neural_net
